import Image from "next/image";
import "../discover.css";

const logo = "/images/vsi logo blue text.png";
const whiteLogo = "/images/VSI LOGO white.png";

const standOnImages = [
  { src: "/images/vsi what we stand on 1.jpg", alt: "VSI What We Stand On" },
  { src: "/images/vsi what we stand on 2.jpg", alt: "VSI What We Stand On" },
  { src: "/images/vsi what we stand on 3.jpg", alt: "VSI What We Stand On" },
  { src: "/images/vsi what we stand on 4.jpg", alt: "VSI What We Stand On" },
  { src: "/images/vsi what we stand on 5.jpg", alt: "VSI What We Stand On" },
  { src: "/images/vsi what we stand on 5.jfif", alt: "VSI What We Stand On" },
  { src: "/images/vsi what we stand on 7.jpg", alt: "VSI What We Stand On" },
  { src: "/images/vsi what we stand on policy.jpg", alt: "VSI policy and public participation" },
];

export default function DiscoverPage() {
  return (
    <main>
      <header className="site-header"><div className="nav-shell"><a className="brand" href="/"><Image src={logo} alt="Visionary Students Initiative" width={188} height={71} priority /></a><nav className="desktop-nav"><a href="/discover">Discover VSI</a><a href="/#work">Our work</a><a href="/story">Our story</a><a href="/volunteer">Volunteer</a><a href="/#contact">Contact</a></nav><a className="nav-cta" href="/volunteer">Volunteer <span>↗</span></a></div></header>
      <section className="discover-hero"><div className="section-shell discover-hero-grid"><div><p className="kicker">DISCOVER VSI</p><h1>Who we are, what we stand on, and <em>why we exist.</em></h1><p>Visionary Students Initiative (VSI) is a Zambian youth-led organisation working to promote policies and initiatives that place students and young people at the centre of national development.</p></div><div className="discover-hero-image"><Image src="/images/vsi-community-action.jpg" alt="VSI volunteers taking part in community action" fill priority sizes="(max-width: 900px) 100vw, 50vw" /></div></div></section>
      <section className="discover-intro section-shell"><div><p className="kicker">WHO WE ARE</p><h2>A youth-led initiative rooted in participation, service and possibility.</h2></div><div><p>We create opportunities for learning, leadership, civic participation, community action, research, dialogue and collaboration.</p><p>Our work is guided by a belief that students are not simply preparing for the future — they are partners in shaping Zambia's future today.</p></div></section>
      <section className="stand-on section-shell">
        <div className="stand-on-heading"><p className="kicker">OUR FOUNDATION</p><h2>WHAT WE STAND ON</h2><p>We, the members of Visionary Students Initiative (VSI), united by a shared commitment to student leadership, democratic participation, social justice, and sustainable development.</p></div>
        <div className="stand-on-visual"><div className="stand-on-lead-image"><Image src="/images/vsi what we stand on lead picture.jpg" alt="VSI What We Stand On" fill sizes="(max-width: 900px) 100vw, 55vw" /></div></div>
        <div className="stand-on-copy"><p><strong>Recognising</strong> that students are vital partners in shaping public policy, advancing innovation, strengthening democratic governance, and contributing to national development, we affirm our collective responsibility to create an inclusive platform through which their voices, ideas, and leadership can meaningfully influence society.</p><p><strong>Guided</strong> by the Constitution of the Republic of Zambia, the principles of good governance, respect for human rights, the rule of law, accountability, integrity, and evidence-based decision-making, we commit ourselves to promoting ethical leadership, active citizenship, research, advocacy, collaboration, and volunteerism.</p><p><strong>Through</strong> the VSI established legal framework, we establish a transparent, accountable, and participatory framework for the governance and administration of Visionary Students Initiative, ensuring that the Organization remains non-profit, non-partisan, inclusive, and dedicated to serving the public interest.</p><p><strong>In this spirit,</strong> we pledge to uphold the Vision, Purpose, Mission, Core Values, and Guiding Principles of Visionary Students Initiative and to work collectively towards empowering students to lead positive change and contribute to inclusive and sustainable national development for present and future generations.</p></div>
      </section>
      <section className="stand-gallery section-shell" aria-label="What We Stand On photo gallery"><div className="stand-gallery-intro"><p className="kicker">OUR COMMITMENT IN PICTURES</p><h2>The people, places and ideas behind our commitments.</h2></div><div className="stand-gallery-grid">{standOnImages.map((image, index) => <figure className={`stand-gallery-card stand-gallery-card-${index + 1}`} key={image.src}><Image src={image.src} alt={image.alt} fill sizes="(max-width: 700px) 100vw, (max-width: 1100px) 50vw, 33vw" /></figure>)}</div></section>
      <section className="discover-facts"><div className="section-shell discover-facts-grid"><article><p className="kicker">LEGAL STATUS</p><h2>Established to serve the public interest.</h2><p>Visionary Students Initiative is a non-profit, non-partisan, non-religious, youth-led, membership-based organization duly registered under the laws of the Republic of Zambia, Department of Registrar of Non-Governmental Organizations, Ministry of Community Development and Social Services</p></article><article><p className="kicker">AREA OF OPERATION</p><h2>Working across Zambia and beyond.</h2><p>VSI operates throughout the Republic of Zambia and undertakes regional or international programmes, partnerships, and collaborations consistent with its Vision, Mission, and applicable laws.</p></article></div></section>
      <section className="membership section-shell"><div className="membership-grid"><div><p className="kicker">MEMBERSHIP</p><h2>Open to people and institutions committed to positive change.</h2></div><div><p>Membership of Visionary Students Initiative (VSI) is open to individuals above the age of sixteen (16) and institutions that subscribe to the Vision, Mission, Core Values, and Objects of the Organization and are committed to promoting student leadership, civic participation, and sustainable national development.</p><p>Membership is voluntary and shall not discriminate on the basis of race, tribe, ethnic origin, colour, sex, disability, religion, political opinion, or socio-economic status.</p></div></div></section>
      <section className="discover-next"><div className="section-shell"><p className="kicker light">KEEP EXPLORING VSI</p><h2>See how our work turns these commitments into action.</h2><a className="button button-yellow" href="/#work">Explore our work <span>↗</span></a></div></section>
      <footer><div className="section-shell footer-grid"><div className="footer-brand"><Image src={whiteLogo} alt="Visionary Students Initiative" width={250} height={94} /><p>Promoting policies and initiatives that place students at the centre of national development.</p></div><div><p className="footer-title">Explore</p><a href="/discover">Discover VSI</a><a href="/#work">Our work</a><a href="/story">Our story</a><a href="/volunteer">Volunteer</a></div><div><p className="footer-title">Contact</p><a href="mailto:vsizambia@gmail.com">vsizambia@gmail.com</a><a href="tel:+260968623786">+260 968 623 786</a><span>Plot No. 9173, Ben Bella Road<br/>Peace Embassy Building, 1st Floor<br/>Lusaka, Zambia</span></div></div><div className="section-shell footer-bottom"><span>© {new Date().getFullYear()} Visionary Students Initiative</span><span>Made for youth-led change in Zambia.</span></div></footer>
    </main>
  );
}
