import {NextResponse} from "next/server";
import {ensureEventsTable,pool} from "../../../../lib/db";
import {isAdminAuthenticated} from "../../../../lib/admin-auth";
const unauthorized=()=>NextResponse.json({error:"Admin authentication required."},{status:401});
const clean=v=>typeof v==="string"?v.trim():"";
const money=v=>Math.max(0,Number(v)||0);
function makeSlug(v){return clean(v).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,90)||`event-${Date.now()}`}
async function uniqueSlug(title,id=null){const base=makeSlug(title);let slug=base,n=2;while(true){const q=id?await pool.query("SELECT id FROM vsi_events WHERE slug=$1 AND id<>$2 LIMIT 1",[slug,id]):await pool.query("SELECT id FROM vsi_events WHERE slug=$1 LIMIT 1",[slug]);if(!q.rowCount)return slug;slug=`${base}-${n++}`}}
function validDate(v){return /^\d{4}-\d{2}-\d{2}$/.test(clean(v))}
function feeData(b){const type=b.fee_type==="paid"?"paid":"free";const amount=type==="paid"?money(b.fee_amount):0;return {type,amount,note:clean(b.fee_note),options:type==="paid"?[{label:`ZMW ${amount.toLocaleString()}`,amount}]:[{label:"Free",amount:0}]}}
function speakersData(value){if(!Array.isArray(value))return [];return value.map((s,i)=>({name:clean(s?.name),title:clean(s?.title),institution:clean(s?.institution),topic:clean(s?.topic),photo_url:clean(s?.photo_url),sort_order:i})).filter(s=>s.name)}
async function getSpeakers(eventIds){if(!eventIds.length)return new Map();const r=await pool.query("SELECT * FROM event_speakers WHERE event_id = ANY($1::bigint[]) ORDER BY event_id,sort_order,id",[eventIds]);const map=new Map();for(const s of r.rows){if(!map.has(String(s.event_id)))map.set(String(s.event_id),[]);map.get(String(s.event_id)).push(s)}return map}
async function withSpeakers(rows){const map=await getSpeakers(rows.map(x=>x.id));return rows.map(x=>({...x,speakers:map.get(String(x.id))||[]}))}
async function replaceSpeakers(eventId,speakers){await pool.query("DELETE FROM event_speakers WHERE event_id=$1",[eventId]);for(const s of speakers){await pool.query("INSERT INTO event_speakers(event_id,name,title,institution,topic,photo_url,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7)",[eventId,s.name,s.title||null,s.institution||null,s.topic||null,s.photo_url||null,s.sort_order])}}
export async function GET(request){if(!isAdminAuthenticated(request))return unauthorized();try{await ensureEventsTable();const r=await pool.query("SELECT * FROM vsi_events ORDER BY event_date ASC,start_time ASC,id DESC");return NextResponse.json({events:await withSpeakers(r.rows)})}catch(e){console.error(e);return NextResponse.json({error:"Unable to load events register."},{status:500})}}
export async function POST(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();const title=clean(b.title),category=clean(b.category),summary=clean(b.summary),content=clean(b.content),eventDate=clean(b.event_date);if(!title||!category||!summary||!content||!validDate(eventDate))return NextResponse.json({error:"Title, category, summary, full details and a valid event date are required."},{status:400});await ensureEventsTable();const status=["draft","published","archived"].includes(b.status)?b.status:"draft";const slug=await uniqueSlug(title);const publishedAt=status==="published"?(b.published_at||new Date().toISOString()):null;const f=feeData(b);const r=await pool.query(`INSERT INTO vsi_events (title,slug,category,summary,content,topic,speaker,featured_image,event_date,start_time,end_time,venue,location,registration_url,contact,directorate,programme,project,status,featured,published_at,fee_type,fee_amount,fee_note,fee_options,contact_name,contact_role,contact_phone,contact_email) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30) RETURNING *`,[title,slug,category,summary,content,clean(b.topic),clean(b.speaker),clean(b.featured_image)||null,eventDate,clean(b.start_time)||null,clean(b.end_time)||null,clean(b.venue)||null,clean(b.location)||null,clean(b.registration_url)||null,clean(b.contact)||null,clean(b.directorate)||null,clean(b.programme)||null,clean(b.project)||null,status,!!b.featured,publishedAt,f.type,f.amount,f.note,JSON.stringify(f.options),clean(b.contact_name)||null,clean(b.contact_role)||null,clean(b.contact_phone)||null,clean(b.contact_email)||null]);const speakers=speakersData(b.speakers);await replaceSpeakers(r.rows[0].id,speakers);return NextResponse.json({ok:true,event:{...r.rows[0],speakers}},{status:201})}catch(e){console.error(e);return NextResponse.json({error:"Unable to create event."},{status:500})}}
export async function PUT(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();if(!b.id)return NextResponse.json({error:"Event ID is required."},{status:400});const title=clean(b.title),category=clean(b.category),summary=clean(b.summary),content=clean(b.content),eventDate=clean(b.event_date);if(!title||!category||!summary||!content||!validDate(eventDate))return NextResponse.json({error:"Title, category, summary, full details and a valid event date are required."},{status:400});await ensureEventsTable();const status=["draft","published","archived"].includes(b.status)?b.status:"draft";const slug=await uniqueSlug(title,b.id);const publishedAt=status==="published"?(b.published_at||new Date().toISOString()):null;const f=feeData(b);const r=await pool.query(`UPDATE vsi_events SET title=$1,slug=$2,category=$3,summary=$4,content=$5,topic=$6,speaker=$7,featured_image=$8,event_date=$9,start_time=$10,end_time=$11,venue=$12,location=$13,registration_url=$14,contact=$15,directorate=$16,programme=$17,project=$18,status=$19,featured=$20,published_at=$21,fee_type=$22,fee_amount=$23,fee_note=$24,fee_options=$25,contact_name=$26,contact_role=$27,contact_phone=$28,contact_email=$29,updated_at=NOW() WHERE id=$30 RETURNING *`,[title,slug,category,summary,content,clean(b.topic),clean(b.speaker),clean(b.featured_image)||null,eventDate,clean(b.start_time)||null,clean(b.end_time)||null,clean(b.venue)||null,clean(b.location)||null,clean(b.registration_url)||null,clean(b.contact)||null,clean(b.directorate)||null,clean(b.programme)||null,clean(b.project)||null,status,!!b.featured,publishedAt,f.type,f.amount,f.note,JSON.stringify(f.options),clean(b.contact_name)||null,clean(b.contact_role)||null,clean(b.contact_phone)||null,clean(b.contact_email)||null,b.id]);if(!r.rowCount)return NextResponse.json({error:"Event not found."},{status:404});const speakers=speakersData(b.speakers);await replaceSpeakers(b.id,speakers);return NextResponse.json({ok:true,event:{...r.rows[0],speakers}})}catch(e){console.error(e);return NextResponse.json({error:"Unable to update event."},{status:500})}}
export async function DELETE(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();if(!b.id)return NextResponse.json({error:"Event ID is required."},{status:400});await ensureEventsTable();const r=await pool.query("DELETE FROM vsi_events WHERE id=$1 RETURNING id",[b.id]);if(!r.rowCount)return NextResponse.json({error:"Event not found."},{status:404});return NextResponse.json({ok:true,id:r.rows[0].id})}catch(e){console.error(e);return NextResponse.json({error:"Unable to delete event."},{status:500})}}
