import { NextResponse } from "next/server";
import { ensureEventsTable, pool } from "../../../../lib/db";
import { isAdminAuthenticated } from "../../../../lib/admin-auth";

const unauthorized=()=>NextResponse.json({error:"Admin authentication required."},{status:401});
const clean=v=>typeof v==="string"?v.trim():"";
function makeSlug(value){return clean(value).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,90)||`event-${Date.now()}`;}
async function uniqueSlug(title,id=null){const base=makeSlug(title);let slug=base,n=2;while(true){const q=id?await pool.query("SELECT id FROM vsi_events WHERE slug=$1 AND id<>$2 LIMIT 1",[slug,id]):await pool.query("SELECT id FROM vsi_events WHERE slug=$1 LIMIT 1",[slug]);if(!q.rowCount)return slug;slug=`${base}-${n++}`;}}
function validDate(v){return /^\d{4}-\d{2}-\d{2}$/.test(clean(v));}

export async function GET(request){if(!isAdminAuthenticated(request))return unauthorized();try{await ensureEventsTable();const r=await pool.query("SELECT * FROM vsi_events ORDER BY event_date ASC,start_time ASC,id DESC");return NextResponse.json({events:r.rows});}catch(e){console.error(e);return NextResponse.json({error:"Unable to load events register."},{status:500});}}

export async function POST(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();const title=clean(b.title),category=clean(b.category),summary=clean(b.summary),content=clean(b.content),eventDate=clean(b.event_date);if(!title||!category||!summary||!content||!validDate(eventDate))return NextResponse.json({error:"Title, category, summary, full details and a valid event date are required."},{status:400});await ensureEventsTable();const status=["draft","published","archived"].includes(b.status)?b.status:"draft";const slug=await uniqueSlug(title);const publishedAt=status==='published'?(b.published_at||new Date().toISOString()):null;const r=await pool.query(`INSERT INTO vsi_events (title,slug,category,summary,content,featured_image,event_date,start_time,end_time,venue,location,registration_url,contact,directorate,programme,project,status,featured,published_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) RETURNING *`,[title,slug,category,summary,content,clean(b.featured_image)||null,eventDate,clean(b.start_time)||null,clean(b.end_time)||null,clean(b.venue)||null,clean(b.location)||null,clean(b.registration_url)||null,clean(b.contact)||null,clean(b.directorate)||null,clean(b.programme)||null,clean(b.project)||null,status,!!b.featured,publishedAt]);return NextResponse.json({ok:true,event:r.rows[0]},{status:201});}catch(e){console.error(e);return NextResponse.json({error:"Unable to create event."},{status:500});}}

export async function PUT(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();if(!b.id)return NextResponse.json({error:"Event ID is required."},{status:400});const title=clean(b.title),category=clean(b.category),summary=clean(b.summary),content=clean(b.content),eventDate=clean(b.event_date);if(!title||!category||!summary||!content||!validDate(eventDate))return NextResponse.json({error:"Title, category, summary, full details and a valid event date are required."},{status:400});await ensureEventsTable();const status=["draft","published","archived"].includes(b.status)?b.status:"draft";const slug=await uniqueSlug(title,b.id);const publishedAt=status==='published'?(b.published_at||new Date().toISOString()):null;const r=await pool.query(`UPDATE vsi_events SET title=$1,slug=$2,category=$3,summary=$4,content=$5,featured_image=$6,event_date=$7,start_time=$8,end_time=$9,venue=$10,location=$11,registration_url=$12,contact=$13,directorate=$14,programme=$15,project=$16,status=$17,featured=$18,published_at=$19,updated_at=NOW() WHERE id=$20 RETURNING *`,[title,slug,category,summary,content,clean(b.featured_image)||null,eventDate,clean(b.start_time)||null,clean(b.end_time)||null,clean(b.venue)||null,clean(b.location)||null,clean(b.registration_url)||null,clean(b.contact)||null,clean(b.directorate)||null,clean(b.programme)||null,clean(b.project)||null,status,!!b.featured,publishedAt,b.id]);if(!r.rowCount)return NextResponse.json({error:"Event not found."},{status:404});return NextResponse.json({ok:true,event:r.rows[0]});}catch(e){console.error(e);return NextResponse.json({error:"Unable to update event."},{status:500});}}

export async function DELETE(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();if(!b.id)return NextResponse.json({error:"Event ID is required."},{status:400});await ensureEventsTable();const r=await pool.query("DELETE FROM vsi_events WHERE id=$1 RETURNING id",[b.id]);if(!r.rowCount)return NextResponse.json({error:"Event not found."},{status:404});return NextResponse.json({ok:true,id:r.rows[0].id});}catch(e){console.error(e);return NextResponse.json({error:"Unable to delete event."},{status:500});}}
