import { NextResponse } from "next/server";
import { ensureVolunteerTable, pool } from "../../../../lib/db";
import { isAdminAuthenticated } from "../../../../lib/admin-auth";

const unauthorized=()=>NextResponse.json({error:"Admin authentication required."},{status:401});
function hoursBetween(start,end){const [sh,sm]=String(start).split(":").map(Number);const [eh,em]=String(end).split(":").map(Number);let minutes=(eh*60+em)-(sh*60+sm);if(minutes<0)minutes+=1440;return Number((minutes/60).toFixed(2));}
export async function GET(request){if(!isAdminAuthenticated(request))return unauthorized();try{await ensureVolunteerTable();const r=await pool.query(`SELECT a.*,v.full_name,v.category FROM volunteer_activity_register a JOIN volunteer_applications v ON v.id=a.volunteer_id ORDER BY a.activity_date DESC,a.start_time DESC`);return NextResponse.json({activities:r.rows});}catch(e){console.error(e);return NextResponse.json({error:"Unable to load activity register."},{status:500});}}
export async function POST(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();if(!b.volunteerId||!b.activityDate||!b.activityName||!b.startTime||!b.endTime)return NextResponse.json({error:"Please complete the required activity fields."},{status:400});const hours=hoursBetween(b.startTime,b.endTime);if(hours<=0)return NextResponse.json({error:"Activity duration must be greater than zero."},{status:400});await ensureVolunteerTable();const r=await pool.query(`INSERT INTO volunteer_activity_register (volunteer_id,activity_date,activity_name,project,location,start_time,end_time,hours,description,supervisor_name,verified) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[b.volunteerId,b.activityDate,b.activityName,b.project||null,b.location||null,b.startTime,b.endTime,hours,b.description||null,b.supervisorName||null,b.verified===true]);return NextResponse.json({activity:r.rows[0]},{status:201});}catch(e){console.error(e);return NextResponse.json({error:"Unable to save activity."},{status:500});}}
export async function PUT(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();if(!b.id)return NextResponse.json({error:"Activity not found."},{status:400});const hours=hoursBetween(b.startTime,b.endTime);if(hours<=0)return NextResponse.json({error:"Activity duration must be greater than zero."},{status:400});await ensureVolunteerTable();const r=await pool.query(`UPDATE volunteer_activity_register SET activity_date=$1,activity_name=$2,project=$3,location=$4,start_time=$5,end_time=$6,hours=$7,description=$8,supervisor_name=$9,verified=$10,updated_at=NOW() WHERE id=$11 RETURNING *`,[b.activityDate,b.activityName,b.project||null,b.location||null,b.startTime,b.endTime,hours,b.description||null,b.supervisorName||null,b.verified===true,b.id]);return NextResponse.json({activity:r.rows[0]});}catch(e){console.error(e);return NextResponse.json({error:"Unable to update activity."},{status:500});}}
export async function DELETE(request){if(!isAdminAuthenticated(request))return unauthorized();try{const {id}=await request.json();if(!id)return NextResponse.json({error:"Activity ID is required."},{status:400});await ensureVolunteerTable();const r=await pool.query(`DELETE FROM volunteer_activity_register WHERE id=$1 RETURNING id`,[id]);if(!r.rowCount)return NextResponse.json({error:"Activity not found."},{status:404});return NextResponse.json({ok:true,id:r.rows[0].id});}catch(e){console.error(e);return NextResponse.json({error:"Unable to delete activity."},{status:500});}}
