"use client";
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {SiteFooter,SiteHeader} from "../../../../components/SiteChrome";
import ProfessionalDevelopment from "./ProfessionalDevelopment";
import styles from "../../admin.module.css";
const booleanFields=["volunteering_elsewhere","criminal_conviction","disability","membership_fee_acknowledged"];
const arrayFields=["programme","project","activity"];
const editFields=[
 ["full_name","Full name","input"],["age","Date of birth (DD/MM/YYYY)","input"],["nationality","Nationality","input"],["gender","Gender","input"],["faith","Faith","input"],["email","Email","email"],["phone","Phone","input"],["province","Province","input"],["district","District","input"],["constituency","Constituency","input"],["ward","Ward","input"],["location","Location","input"],["current_occupation","Current occupation","input"],["education","Education","input"],["category","Volunteer area","input"],["skills","Skills","textarea"],["availability","Availability","textarea"],["hours_per_week","Hours per week","input"],["motivation","Motivation","textarea"],["volunteering_elsewhere","Volunteering elsewhere","boolean"],["other_volunteering_details","Other volunteering details","textarea"],["past_volunteer_positions","Past volunteer positions","textarea"],["reference_name","Reference name","input"],["reference_organization","Reference organization","input"],["reference_phone","Reference phone","input"],["reference_email","Reference email","email"],["criminal_conviction","Criminal conviction","boolean"],["criminal_offence_details","Criminal offence details","textarea"],["disability","Disability","boolean"],["disability_certificate","Disability certificate","textarea"],["disability_certificate_name","Disability certificate name","input"],["profile_picture","Profile picture URL","input"],["emergency_name","Emergency contact name","input"],["emergency_phone","Emergency contact phone","input"],["membership_fee_acknowledged","Membership fee acknowledged","boolean"],["directorate","Directorate","input"],["programme","Programme (comma separated)","input"],["project","Project (comma separated)","input"],["activity","Activity (comma separated)","input"],["line_manager_name","Supervisor name","input"],["line_manager_title","Supervisor title","input"],["line_manager_phone","Supervisor phone","input"],["line_manager_email","Supervisor email","email"]
];
const arrayValue=v=>Array.isArray(v)?v.join(", "):typeof v==="number"?String(v):typeof v==="string"&&v.trim()?(()=>{try{const p=JSON.parse(v);return Array.isArray(p)?p.join(", "):v}catch{return v}})():"";
const booleanValue=v=>v===true||v==="true"||v===1||v==="1";
export default function VolunteerProfile(){
 const {id}=useParams(),router=useRouter(); const [volunteer,setVolunteer]=useState(null),[activities,setActivities]=useState([]),[hours,setHours]=useState({week:0,total:0}),[error,setError]=useState(""),[editing,setEditing]=useState(false),[draft,setDraft]=useState({}),[saving,setSaving]=useState(false),[saveMessage,setSaveMessage]=useState("");
 async function load(){try{const r=await fetch("/api/admin/volunteers",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load volunteer profile.");const v=(d.applications||[]).find(x=>String(x.id)===String(id));if(!v)throw new Error("Volunteer profile not found.");const ar=await fetch(`/api/admin/activity?volunteerId=${encodeURIComponent(id)}`,{cache:"no-store"}),ad=await ar.json();if(!ar.ok)throw new Error(ad.error||"Unable to load activity history.");setVolunteer(v);setActivities(ad.activities||[]);setHours({week:Number(ad.week_hours||0),total:Number(ad.total_hours||0)});return v}catch(e){setError(e.message)}}
 useEffect(()=>{let alive=true;(async()=>{const v=await load();if(!alive)return})();return()=>{alive=false}},[id]);
 function beginEdit(){if(!volunteer)return;const d={};editFields.forEach(([key])=>{if(booleanFields.includes(key))d[key]=booleanValue(volunteer[key]);else d[key]=arrayValue(volunteer[key])});setDraft(d);setSaveMessage("");setError("");setEditing(true)}
 function setValue(key,value){setDraft(d=>({...d,[key]:value}))}
 async function saveEdit(e){e.preventDefault();setSaving(true);setError("");setSaveMessage("");try{const payload={id};editFields.forEach(([key])=>{let v=draft[key];if(booleanFields.includes(key)){v=booleanValue(v)}else if(arrayFields.includes(key)){v=String(v??"").split(",").map(x=>x.trim()).filter(Boolean)}else{v=v??""}payload[key]=v});const r=await fetch("/api/admin/volunteers",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save volunteer profile.");setEditing(false);setSaveMessage("Volunteer profile updated successfully.");await load();}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function changeStatus(next){setError("");if(next==="pending"&&!window.confirm(`Unapprove ${volunteer.full_name}? The volunteer will return to pending status.`))return;try{const r=await fetch("/api/admin/volunteers",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:next,rejectionReason:null,rejectionNote:"",directorate:volunteer.directorate||"",programme:volunteer.programme||[],project:volunteer.project||[],lineManagerName:volunteer.line_manager_name||"",lineManagerTitle:volunteer.line_manager_title||"",lineManagerPhone:volunteer.line_manager_phone||"",lineManagerEmail:volunteer.line_manager_email||""})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to update volunteer status.");await load();setSaveMessage(next==="pending"?"Volunteer has been unapproved and returned to pending status.":"Volunteer approved successfully")}catch(e){setError(e.message)}}
 if(error&&!volunteer)return <><SiteHeader ctaLabel="Volunteer Register" ctaHref="/admin/volunteers"/><main className={styles.page}><div className={styles.shell}><div className={styles.empty}>{error}<br/><button className={styles.saveReview} onClick={()=>router.push("/admin/volunteers")}>Back to Volunteer Register</button></div></div></main><SiteFooter/></>;
 if(!volunteer)return <><SiteHeader ctaLabel="Volunteer Register" ctaHref="/admin/volunteers"/><main className={styles.page}><div className={styles.shell}><div className={styles.empty}>Loading volunteer profile…</div></div></main><SiteFooter/></>;
 const initials=volunteer.full_name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase();
 return <><SiteHeader ctaLabel="Volunteer Register" ctaHref="/admin/volunteers"/><main className={styles.page}><div className={styles.shell}><div className={styles.topline}><span>VSI IMS <b>/</b> Volunteer Profile</span><button onClick={()=>router.push("/admin/volunteers")}>← Volunteer Register</button></div><section className={styles.hero}><div><p className="kicker light">VOLUNTEER PROFILE</p><h1>{volunteer.full_name}</h1><p>{volunteer.volunteer_id||"VSI Volunteer"} · {volunteer.status||""}</p></div></section>{saveMessage&&<div className={styles.success}>{saveMessage}</div>}{error&&<div className={styles.error}>{error}</div>}
 <section className={styles.registerPanel} style={{marginTop:18}}><div className={styles.registerHeader}><div><p className="kicker">PROFILE ACTIONS</p><h2>Manage volunteer</h2></div><div style={{display:"flex",gap:8,flexWrap:"wrap",justifyContent:"flex-end"}}>{volunteer.status==="approved"?<button className={styles.actionReject} onClick={()=>changeStatus("pending")}>↶ Unapprove</button>:<button className={styles.actionApprove} onClick={()=>changeStatus("approved")}>✓ Approve</button>}<button className={styles.actionEdit} onClick={beginEdit}>✎ Edit profile</button></div></div></section>
 {editing?<form className={styles.registerPanel} style={{marginTop:18,padding:28}} onSubmit={saveEdit}><div className={styles.registerHeader} style={{marginBottom:20}}><div><p className="kicker">EDIT VOLUNTEER</p><h2>Complete volunteer profile</h2></div><span>All profile fields are editable.</span></div><div className={styles.detailGrid} style={{gridTemplateColumns:"repeat(2,minmax(0,1fr))"}}>{editFields.map(([key,label,type])=><label key={key} style={{display:"flex",flexDirection:"column",gap:7,fontWeight:700}}><span>{label}</span>{type==="textarea"?<textarea rows={3} value={draft[key]??""} onChange={e=>setValue(key,e.target.value)} style={{width:"100%",boxSizing:"border-box"}}/>:type==="boolean"?<select value={draft[key]?"true":"false"} onChange={e=>setValue(key,e.target.value==="true")} style={{width:"100%",boxSizing:"border-box"}}><option value="true">Yes</option><option value="false">No</option></select>:<input type={type==="email"?"email":"text"} value={draft[key]??""} onChange={e=>setValue(key,e.target.value)} style={{width:"100%",boxSizing:"border-box"}}/>}</label>)}</div><div style={{display:"flex",gap:10,marginTop:24,flexWrap:"wrap"}}><button type="submit" className={styles.saveReview} disabled={saving}>{saving?"Saving…":"Save changes"}</button><button type="button" className={styles.clearButton} onClick={()=>setEditing(false)} disabled={saving}>Cancel</button></div></form>:<section className={styles.registerPanel} style={{marginTop:18}}><div className={styles.profileGrid} style={{padding:28,alignItems:"flex-start"}}><div>{volunteer.profile_picture?<img className={styles.profileLarge} style={{width:96,height:118}} src={volunteer.profile_picture} alt={volunteer.full_name}/>:<div className={styles.avatar} style={{width:96,height:118,borderRadius:15,fontSize:24}}>{initials}</div>}</div><div className={styles.detailGrid}><div><span>VSI ID</span><strong>{volunteer.volunteer_id||"—"}</strong></div>{editFields.filter(([k])=>!["profile_picture","programme","project","activity"].includes(k)).map(([key,label])=><div key={key}><span>{label}</span><strong>{booleanFields.includes(key)?(booleanValue(volunteer[key])?"Yes":"No"):(arrayValue(volunteer[key])||"—")}</strong></div>)}<div><span>Programme</span><strong>{arrayValue(volunteer.programme)||"—"}</strong></div><div><span>Project</span><strong>{arrayValue(volunteer.project)||"—"}</strong></div><div><span>Activity</span><strong>{arrayValue(volunteer.activity)||"—"}</strong></div></div></div></section>}
 <section className={styles.registerPanel} style={{marginTop:18}}><div className={styles.registerHeader}><div><p className="kicker">VOLUNTEER HOURS</p><h2>Activity History</h2></div><strong>Total verified: {hours.total.toFixed(2)} hrs</strong></div><div className={styles.hoursSummary} style={{margin:"0 28px 18px"}}><div><span>THIS WEEK</span><strong>{hours.week.toFixed(2)} / 6 hrs</strong></div><div><span>TOTAL VERIFIED HOURS</span><strong>{hours.total.toFixed(2)} hrs</strong></div><div><span>ACTIVITIES</span><strong>{activities.length}</strong></div></div>{activities.length===0?<div className={styles.empty}>No activity has been recorded yet.</div>:<div className={styles.historyList} style={{padding:"0 28px 28px"}}>{activities.map(a=><div className={styles.historyItem} key={a.id}><div><strong>{a.activity_name}</strong><span>{a.activity_date} · {a.start_time?.slice(0,5)}–{a.end_time?.slice(0,5)} · {a.project||"No project"} · {a.location||"Location not recorded"}</span>{a.description&&<span><b>Role / Contribution:</b> {a.description}</span>}</div><div><b>{Number(a.hours).toFixed(2)} hrs</b><em className={a.verified?styles.verified:styles.unverified}>{a.verified?"Verified":"Unverified"}</em></div></div>)}</div>}</section>
 <ProfessionalDevelopment volunteerId={id}/>
 </div></main><SiteFooter/></>;
}
