"use client";
import {useEffect,useState} from "react";
import Image from "next/image";
import CookieConsent from "./CookieConsent";
const logo="/images/vsi logo blue text.png",whiteLogo="/images/VSI LOGO white.png";
const socialLinks=[["Facebook","https://web.facebook.com/vsizambia","/icons/facebook.svg"],["Instagram","https://www.instagram.com/vsizambia","/icons/instagram.svg"],["YouTube","https://www.youtube.com/@vsizambia","/icons/youtube.svg"],["LinkedIn","https://www.linkedin.com/in/visionary-students-initiative-vsi-0a4472382/","/icons/linkedin.svg"]];
const defaults={header:{links:[["Discover VSI","/discover"],["Our work","/#work"],["Our story","/story"],["Impact & Evidence","/impact"],["Community","/community"],["VSI News","/news"],["Events","/events"],["Volunteer","/volunteer"],["Contact","/#contact"]],ctaLabel:"Volunteer",ctaHref:"/volunteer"},footer:{brandText:"Promoting policies and initiatives that place students at the centre of national development.",explore:[["Home","/"],["Discover VSI","/discover"],["Our work","/#work"],["Our story","/story"],["Impact & Evidence","/impact"],["VSI in the Community","/community"],["VSI News","/news"],["Events","/events"],["Volunteer","/volunteer"]],email:"vsizambia@gmail.com",phone:"+260 968 623 786",address:"Plot No. 9173, Ben Bella Road\nPeace Embassy Building, 1st Floor\nLusaka, Zambia"}};
function ensureImpactLink(key,content){if(!content)return defaults[key];const next={...content};const field=key==="header"?"links":"explore";const links=Array.isArray(next[field])?next[field]:[];if(!links.some(([label,href])=>label==="Impact & Evidence"||href==="/impact")){const copy=[...links];const anchor=copy.findIndex(([label])=>label==="Our story");copy.splice(anchor>=0?anchor+1:0,0,["Impact & Evidence","/impact"]);next[field]=copy}return next}
function useChrome(key){const[config,setConfig]=useState(defaults[key]);useEffect(()=>{let alive=true;const cacheBust=Date.now();fetch(`/api/website-chrome?key=${encodeURIComponent(key)}&_=${cacheBust}`,{cache:"no-store",headers:{"Cache-Control":"no-cache"}}).then(r=>r.ok?r.json():null).then(d=>{if(alive&&d?.content)setConfig(ensureImpactLink(key,d.content))}).catch(()=>{});return()=>{alive=false}},[key]);return config}
export function SiteHeader({ctaLabel,ctaHref}={}){const cfg=useChrome("header");const finalLabel=ctaLabel??cfg.ctaLabel,finalHref=ctaHref??cfg.ctaHref,isAdmin=finalHref.startsWith("/admin");return <header className="site-header"><nav className="vsi-top-ribbon" aria-label="VSI social links"><div className="vsi-top-ribbon-inner"><div className="vsi-top-ribbon-left" aria-hidden="true"/><div className="vsi-top-ribbon-right">{socialLinks.map(([label,href,icon])=><a key={label} href={href} target="_blank" rel="noopener noreferrer" aria-label={`VSI on ${label}`}><Image src={icon} alt="" width={18} height={18}/></a>)}</div></div></nav><div className="nav-shell"><a className="brand" href="/" aria-label="Visionary Students Initiative home"><Image src={logo} alt="Visionary Students Initiative" width={188} height={71} priority/></a><nav className="desktop-nav" aria-label="Primary navigation">{cfg.links.map(([label,href])=><a key={label+href} href={href}>{label}</a>)}</nav><a className="nav-cta" href={finalHref}>{finalLabel} <span aria-hidden="true">↗</span></a><details className="mobile-menu"><summary aria-label="Open navigation menu"><span/></summary><nav className="mobile-menu-panel" aria-label="Mobile navigation">{cfg.links.map(([label,href])=><a key={label+href} href={href}>{label}</a>)}</nav></details></div>{isAdmin&&<nav aria-label="Admin navigation" style={{display:"flex",justifyContent:"center",gap:"8px",flexWrap:"wrap",padding:"10px 20px",background:"#f4f7fa",borderTop:"1px solid rgba(11,48,82,.08)",borderBottom:"1px solid rgba(11,48,82,.10)"}}><a href="/admin" style={{fontWeight:700,color:"#0B3052"}}>VSI Administration</a></nav>}</header>}
export function SiteFooter({includeNews=true}={}){const cfg=useChrome("footer");const addressLines=String(cfg.address||"").split("\n");return <><footer id="contact"><div className="section-shell footer-grid"><div className="footer-brand"><Image src={whiteLogo} alt="Visionary Students Initiative" width={250} height={94}/><p>{cfg.brandText}</p></div><nav aria-label="Footer navigation" style={{display:"flex",flexDirection:"column",gap:10,alignItems:"flex-start"}}><p className="footer-title">Explore</p>{(cfg.explore||[]).filter(([label])=>includeNews||label!=="VSI News").map(([label,href])=><a key={label+href} href={href}>{label}{["VSI News","Events"].includes(label)&&<span aria-hidden="true"> ↗</span>}</a>)}</nav><div><p className="footer-title">Contact</p><a href={`mailto:${cfg.email}`}>{cfg.email}</a><a href={`tel:${String(cfg.phone||"").replace(/[^+\d]/g,"")}`}>{cfg.phone}</a><span>{addressLines.map((x,i)=><span key={i}>{x}{i<addressLines.length-1&&<br/>}</span>)}</span></div></div><div className="section-shell footer-bottom"><span>© {new Date().getFullYear()} Visionary Students Initiative</span><span>Made for youth-led change in Zambia.</span></div></footer><div className="vsi-legal-footer-links" style={{display:"flex",justifyContent:"center",gap:"18px",flexWrap:"wrap",padding:"14px 20px",background:"#002d55",borderTop:"1px solid rgba(255,255,255,.12)"}}><a href="/privacy-policy" style={{color:"#fff",fontSize:"12px",fontWeight:700,textDecoration:"none"}}>Privacy Policy</a><a href="/data-protection" style={{color:"#fff",fontSize:"12px",fontWeight:700,textDecoration:"none"}}>Data Protection</a></div><CookieConsent/></>}
