"use client";
import {useEffect,useState} from "react";
import Image from "next/image";
import CookieConsent from "./CookieConsent";
const logo="/images/vsi logo blue text.png",whiteLogo="/images/VSI LOGO white.png";
const socialLinks=[["Facebook","https://web.facebook.com/vsizambia","/icons/facebook.svg"],["Instagram","https://www.instagram.com/vsizambia","/icons/instagram.svg"],["YouTube","https://www.youtube.com/@vsizambia","/icons/youtube.svg"],["LinkedIn","https://www.linkedin.com/in/visionary-students-initiative-vsi-0a4472382/","/icons/linkedin.svg"]];
const defaults={header:{links:[["Discover VSI","/discover"],["VSI in Action","/projects"],["Impact & Evidence","/impact"],["Community Voices","/community"],["E-Learning","/elearning"],["VSI News","/news"],["Events","/events"],["Volunteer","/volunteer"],["Contact","/#contact"]],ctaLabel:"Volunteer",ctaHref:"/volunteer"},footer:{brandText:"Promoting policies and initiatives that place students at the centre of national development.",explore:[["Home","/"],["Discover VSI","/discover"],["VSI in Action","/projects"],["Impact & Evidence","/impact"],["Community Voices","/community"],["E-Learning","/elearning"],["VSI News","/news"],["Events","/events"],["Volunteer","/volunteer"]],email:"vsizambia@gmail.com",phone:"+260 968 623 786",address:"Plot No. 9173, Ben Bella Road\nPeace Embassy Building, 1st Floor\nLusaka, Zambia"}};
function cleanNavigation(key,content){if(!content)return defaults[key];const next={...content};const field=key==="header"?"links":"explore";const links=Array.isArray(next[field])?next[field]:[];next[field]=links.filter(([label,href])=>!["Our story","VSI in the Community","Projects & Impact"].includes(label)&&href!=="/story");const existing=new Set(next[field].map(([label,href])=>label+href));const additions=defaults[key][field].filter(([label,href])=>!existing.has(label+href));next[field]=[...next[field],...additions];return next}
function useChrome(key){const[config,setConfig]=useState(defaults[key]);useEffect(()=>{let alive=true;const cacheBust=Date.now();fetch(`/api/website-chrome?key=${encodeURIComponent(key)}&_=${cacheBust}`,{cache:"no-store",headers:{"Cache-Control":"no-cache"}}).then(r=>r.ok?r.json():null).then(d=>{if(alive&&d?.content)setConfig(cleanNavigation(key,d.content))}).catch(()=>{});return()=>{alive=false}},[key]);return config}
export function SiteHeader({ctaLabel,ctaHref,className=""}={}){const cfg=useChrome("header");const finalLabel=ctaLabel??cfg.ctaLabel,finalHref=ctaHref??cfg.ctaHref,isAdmin=finalHref.startsWith("/admin");return <header className={`site-header ${className}`.trim()}><nav className="vsi-top-ribbon" aria-label="VSI social links"><div className="vsi-top-ribbon-inner"><div className="vsi-top-ribbon-left" aria-hidden="true"/><div className="vsi-top-ribbon-right">{socialLinks.map(([label,href,icon])=><a key={label} href={href} target="_blank" rel="noopener noreferrer" aria-label={`VSI on ${label}`}><Image src={icon} alt="" width={18} height={18}/></a>)}</div></div></nav><div className="nav-shell"><a className="brand" href="/" aria-label="Visionary Students Initiative home"><Image src={logo} alt="Visionary Students Initiative" width={188} height={71} priority/></a><nav className="desktop-nav" aria-label="Primary navigation">{cfg.links.map(([label,href])=><a key={label+href} href={href}>{label}</a>)}</nav><a className="nav-cta" href={finalHref}>{finalLabel} <span aria-hidden="true">↗</span></a><details className="mobile-menu"><summary aria-label="Open navigation menu"><span/></summary><nav className="mobile-menu-panel" aria-label="Mobile navigation">{cfg.links.map(([label,href])=><a key={label+href} href={href}>{label}</a>)}</nav></details></div>{isAdmin&&<nav aria-label="Admin navigation" style={{display:"flex",justifyContent:"center",gap:"8px",flexWrap:"wrap",padding:"10px 20px",background:"#f4f7fa",borderTop:"1px solid rgba(11,48,82,.08)",borderBottom:"1px solid rgba(11,48,82,.10)"}}><a href="/admin" style={{fontWeight:700,color:"#0B3052"}}>VSI Administration</a></nav>}</header>}
export function SiteFooter({className=""}){return <div className={className}><footer id="contact" className="vsi-compact-footer"><div className="vsi-compact-footer-inner"><span className="vsi-copyright">© {new Date().getFullYear()} Visionary Students Initiative</span><nav className="vsi-legal-links" aria-label="Legal links"><a href="/privacy-policy">Privacy Policy</a><a href="/data-protection">Data Protection</a></nav><address>Plot No. 9173, Ben Bella Road<br/>Peace Embassy Building, 1st Floor, Lusaka District, Zambia</address></div></footer><CookieConsent/><style jsx>{`
.vsi-compact-footer{background:#002d55;color:#fff;padding:15px 24px}
.vsi-compact-footer-inner{max-width:1220px;margin:0 auto;display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap;font-size:12px;line-height:1.5}
.vsi-compact-footer .vsi-copyright{white-space:nowrap}
.vsi-compact-footer .vsi-legal-links{display:flex;align-items:center;gap:16px}
.vsi-compact-footer a{color:#fff;text-decoration:underline;text-underline-offset:3px}
.vsi-compact-footer address{font-style:normal;text-align:right;max-width:100%;line-height:1.45}
@media(max-width:700px){.vsi-compact-footer{padding:16px}.vsi-compact-footer-inner{justify-content:flex-start;gap:9px 16px}.vsi-compact-footer address{text-align:left;flex-basis:100%}.vsi-compact-footer .vsi-legal-links{gap:14px}}
`}</style></div>}
