"use client";
import {useEffect,useState} from "react";
import {SiteFooter,SiteHeader} from "../../components/SiteChrome";
import styles from "./news.module.css";

const blank={title:"",category:"",excerpt:"",content:"",featured_image:"",author:"",directorate:"",programme:"",project:"",status:"draft",featured:false};
const categories=["Youth Empowerment","Education","Community","Civic Leadership","Research & Advocacy","Announcements","Partnerships","Other"];

export default function NewsAdmin(){
 const[authenticated,setAuthenticated]=useState(false),[password,setPassword]=useState(""),[loginError,setLoginError]=useState(""),[articles,setArticles]=useState([]),[form,setForm]=useState(blank),[selectedId,setSelectedId]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/news",{cache:"no-store"}),d=await r.json();if(r.status===401){setAuthenticated(false);return;}if(!r.ok)throw new Error(d.error);setAuthenticated(true);setArticles(d.articles||[]);}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function login(e){e.preventDefault();setLoginError("");const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const d=await r.json();if(!r.ok){setLoginError(d.error||"Unable to sign in.");return;}setPassword("");load()}
 async function logout(){await fetch("/api/admin/login",{method:"DELETE"});setAuthenticated(false);setArticles([])}
 function change(e){const{name,value,type,checked}=e.target;setForm(x=>({...x,[name]:type==="checkbox"?checked:value}))}
 function newStory(){setSelectedId(null);setForm(blank);setError("");setNotice("");window.scrollTo({top:0,behavior:"smooth"})}
 function edit(a){setSelectedId(a.id);setForm({title:a.title||"",category:a.category||"",excerpt:a.excerpt||"",content:a.content||"",featured_image:a.featured_image||"",author:a.author||"",directorate:a.directorate||"",programme:a.programme||"",project:a.project||"",status:a.status||"draft",featured:!!a.featured});setNotice("");setError("");window.scrollTo({top:0,behavior:"smooth"})}
 async function save(e){e.preventDefault();setSaving(true);setError("");setNotice("");try{const method=selectedId?"PUT":"POST",body=selectedId?{...form,id:selectedId}:form;const r=await fetch("/api/admin/news",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save story.");setArticles(xs=>selectedId?xs.map(x=>x.id===selectedId?d.article:x):[d.article,...xs]);setSelectedId(d.article.id);setForm({title:d.article.title,category:d.article.category,excerpt:d.article.excerpt,content:d.article.content,featured_image:d.article.featured_image||"",author:d.article.author||"",directorate:d.article.directorate||"",programme:d.article.programme||"",project:d.article.project||"",status:d.article.status,featured:!!d.article.featured});setNotice(d.article.status==="published"?"Story published successfully — it is now live on VSI News.":"Draft saved successfully.");}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function remove(a){if(!window.confirm(`Delete “${a.title}” permanently? This cannot be undone.`))return;const r=await fetch("/api/admin/news",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:a.id})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to delete story.");return;}setArticles(xs=>xs.filter(x=>x.id!==a.id));if(selectedId===a.id)newStory();}
 if(!authenticated)return <><SiteHeader ctaLabel="Back to site" ctaHref="/"/><main className={styles.loginPage}><div className={styles.loginShell}><div className={styles.loginMark}>VSI</div><p className="kicker">ADMIN ACCESS</p><h1>News Publishing</h1><p>Sign in to create, edit and publish VSI stories and updates.</p><form onSubmit={login} className={styles.loginForm}><label htmlFor="admin-password">Admin password</label><input id="admin-password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/>{loginError&&<div className={styles.error}>{loginError}</div>}<button type="submit">Sign in <span>↗</span></button></form></div></main><SiteFooter/></>;
 return <><SiteHeader ctaLabel="Public site" ctaHref="/"/><main className={styles.page}><div className={styles.shell}><div className={styles.topline}><span>VSI IMS <b>/</b> News Publishing</span><div><span className={styles.connected}><i/> Connected</span><button onClick={load}>Refresh ↻</button><button onClick={logout}>Log out ↪</button></div></div><section className={styles.hero}><div><p className="kicker light">CONTENT &amp; COMMUNICATIONS</p><h1>News Publishing</h1><p>Create stories once and publish them directly to the VSI website.</p></div><button className={styles.heroButton} onClick={newStory}>+ New story</button></section>
 <div className={styles.grid}><section className={styles.editor}><div className={styles.panelHead}><div><p className="kicker">STORY EDITOR</p><h2>{selectedId?"Edit story":"Create a news story"}</h2></div>{selectedId&&<span className={styles.badge}>{form.status}</span>}</div>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}<form onSubmit={save}><label>Story title<input name="title" value={form.title} onChange={change} placeholder="Enter a clear, engaging headline" required/></label><div className={styles.two}><label>Category<select name="category" value={form.category} onChange={change} required><option value="">Select category</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Author / byline<input name="author" value={form.author} onChange={change} placeholder="e.g. VSI Communications"/></label></div><label>Short summary<textarea name="excerpt" value={form.excerpt} onChange={change} placeholder="This appears on news cards and previews." rows="3" required/></label><label>Full story<textarea className={styles.storyArea} name="content" value={form.content} onChange={change} placeholder="Write the full story here..." rows="12" required/></label><label>Featured image URL<input name="featured_image" value={form.featured_image} onChange={change} placeholder="https://... or /images/..."/><small>For this first version, use an existing public image path or image URL. We can add a direct image uploader next.</small></label><div className={styles.two}><label>Directorate<input name="directorate" value={form.directorate} onChange={change}/></label><label>Programme<input name="programme" value={form.programme} onChange={change}/></label></div><label>Project<input name="project" value={form.project} onChange={change}/></label><div className={styles.publishBox}><label>Status<select name="status" value={form.status} onChange={change}><option value="draft">Draft — keep private</option><option value="published">Publish — make live</option><option value="archived">Archive — remove from public</option></select></label><label className={styles.check}><input type="checkbox" name="featured" checked={form.featured} onChange={change}/> Feature this story</label></div><div className={styles.actions}><button type="submit" disabled={saving}>{saving?"Saving...":form.status==="published"?"Publish story ↗": "Save draft"}</button>{selectedId&&<button type="button" className={styles.secondary} onClick={()=>remove(articles.find(x=>x.id===selectedId))}>Delete</button>}</div></form></section>
 <aside className={styles.register}><div className={styles.panelHead}><div><p className="kicker">NEWS REGISTER</p><h2>Stories</h2></div><strong>{articles.length}</strong></div>{loading?<div className={styles.empty}>Loading stories...</div>:articles.length===0?<div className={styles.empty}>No stories yet. Create the first one.</div>:<div className={styles.storyList}>{articles.map(a=><article key={a.id} className={styles.storyRow}><div><span className={`${styles.status} ${styles[`status_${a.status}`]}`}>{a.status}</span><h3>{a.title}</h3><p>{a.category} · {a.published_at?new Date(a.published_at).toLocaleDateString("en-GB"):"Not published"}</p></div><button onClick={()=>edit(a)}>Edit</button></article>)}</div>}</aside></div></div></main><SiteFooter/></>;
}
