"use client";
import {useState} from "react";
import {SiteFooter,SiteHeader} from "../components/SiteChrome";
import styles from "../legal.module.css";

export default function DataRightsPage(){
 const [form,setForm]=useState({requestType:"access",requesterName:"",requesterEmail:"",details:""});
 const [status,setStatus]=useState("");
 const submit=async e=>{e.preventDefault();setStatus("");const r=await fetch("/api/data-protection-request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();setStatus(r.ok?"Your request has been received. VSI may contact you to verify your identity before releasing personal information.":(d.error||"Unable to submit request."));if(r.ok)setForm({requestType:"access",requesterName:"",requesterEmail:"",details:""});};
 return <><SiteHeader/><main className={styles.page}><article className={styles.shell}><p className="kicker">PRIVACY & DATA PROTECTION</p><h1>Request your data</h1><p className={styles.lead}>Use this form to request access to, correction of, or other information about personal data VSI holds about you, or to withdraw consent where applicable.</p><form onSubmit={submit} style={{display:"grid",gap:16,marginTop:28}}><label>Request type<select value={form.requestType} onChange={e=>setForm({...form,requestType:e.target.value})}><option value="access">Access my personal data</option><option value="correction">Correct my personal data</option><option value="deletion">Request deletion</option><option value="withdraw_consent">Withdraw consent</option><option value="processing_information">Information about processing</option><option value="complaint">Privacy complaint</option></select></label><label>Full name<input required value={form.requesterName} onChange={e=>setForm({...form,requesterName:e.target.value})}/></label><label>Email address<input required type="email" value={form.requesterEmail} onChange={e=>setForm({...form,requesterEmail:e.target.value})}/></label><label>Details<textarea rows="6" value={form.details} onChange={e=>setForm({...form,details:e.target.value})} placeholder="Tell us what information or action you are requesting."/></label><button type="submit">Submit data protection request</button></form>{status&&<p className={styles.note}>{status}</p>}<p className={styles.updated}>For security, VSI may need to verify your identity before providing personal data or acting on a request.</p></article></main><SiteFooter/></>;
}