"use client";
import {useEffect,useMemo,useState} from "react";
import {SiteFooter,SiteHeader} from "../../components/SiteChrome";
import styles from "../volunteers/admin.module.css";

const inputStyle={width:"100%",boxSizing:"border-box",padding:"12px 13px",border:"1px solid #bcccdc",borderRadius:11,fontSize:14,fontFamily:"inherit",color:"#102a43",background:"#fff",outline:"none"};
const th={textAlign:"left",padding:"13px 12px",fontSize:10,color:"#829ab1",textTransform:"uppercase",letterSpacing:".08em",fontWeight:900,borderBottom:"1px solid #e8edf2",whiteSpace:"nowrap"};
const td={padding:"15px 12px",borderBottom:"1px solid #eef2f6",fontSize:13,verticalAlign:"top",color:"#486581"};
const action={border:0,borderRadius:9,padding:"9px 12px",fontSize:12,fontWeight:850,cursor:"pointer",display:"inline-flex",alignItems:"center",justifyContent:"center",gap:5};

export default function EventRegistrationsAdmin(){
 const[authenticated,setAuthenticated]=useState(false),[password,setPassword]=useState(""),[loginError,setLoginError]=useState("");
 const[events,setEvents]=useState([]),[selectedId,setSelectedId]=useState(""),[registrations,setRegistrations]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState("");
 const[selected,setSelected]=useState(null),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");

 async function loadEvents(){
  setLoading(true);setError("");
  try{const r=await fetch("/api/admin/events",{cache:"no-store"});const d=await r.json();if(r.status===401){setAuthenticated(false);return}if(!r.ok)throw Error(d.error||"Unable to load events.");setAuthenticated(true);const list=d.events||[];setEvents(list);if(!selectedId&&list.length)setSelectedId(String(list[0].id));}
  catch(e){setError(e.message)}finally{setLoading(false)}
 }
 async function loadRegistrations(id){
  if(!id){setRegistrations([]);return}setLoading(true);setError("");
  try{const r=await fetch(`/api/admin/event-registrations?event_id=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json();if(r.status===401){setAuthenticated(false);return}if(!r.ok)throw Error(d.error||"Unable to load registrations.");setRegistrations(d.registrations||[])}catch(e){setError(e.message)}finally{setLoading(false)}
 }
 useEffect(()=>{loadEvents()},[]);
 useEffect(()=>{if(authenticated&&selectedId)loadRegistrations(selectedId)},[selectedId,authenticated]);
 async function login(e){e.preventDefault();setLoginError("");const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const d=await r.json();if(!r.ok){setLoginError(d.error||"Unable to sign in.");return}setPassword("");await loadEvents()}
 async function logout(){await fetch("/api/admin/login",{method:"DELETE"});setAuthenticated(false);setEvents([]);setRegistrations([])}
 async function remove(id){if(!confirm("Delete this event registration permanently? This cannot be undone."))return;setError("");const r=await fetch(`/api/admin/event-registrations?id=${encodeURIComponent(id)}`,{method:"DELETE"});const d=await r.json();if(!r.ok){setError(d.error||"Unable to delete registration.");return}setRegistrations(xs=>xs.filter(x=>x.id!==id));setNotice("Registration deleted successfully.");setSelected(null)}
 async function save(){if(!selected)return;setSaving(true);setError("");setNotice("");try{const r=await fetch("/api/admin/event-registrations",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(selected)});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to save registration.");setRegistrations(xs=>xs.map(x=>x.id===d.registration.id?d.registration:x));setSelected(d.registration);setNotice("Registration updated successfully.")}catch(e){setError(e.message)}finally{setSaving(false)}}
 const event=events.find(x=>String(x.id)===String(selectedId));
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return registrations;return registrations.filter(r=>[r.full_name,r.email,r.phone,r.organization,r.province,r.district,r.designation,r.gender,r.disability].some(v=>String(v||"").toLowerCase().includes(q)))},[registrations,search]);
 const totalAmount=registrations.reduce((n,r)=>n+Number(r.fee_amount||0),0);
 const paidRegistrations=registrations.filter(r=>r.payment_status==="paid");
 const regrets=registrations.filter(r=>r.attendance_status==="regrets");
 const expectedAttendees=registrations.filter(r=>r.attendance_status!=="regrets");
 const outstandingAmount=registrations.filter(r=>r.payment_status!=="paid"&&r.payment_status!=="waived").reduce((n,r)=>n+Number(r.fee_amount||0),0);
 const paidAmount=paidRegistrations.reduce((n,r)=>n+Number(r.fee_amount||0),0);
 const waivedAmount=registrations.filter(r=>r.payment_status==="waived").reduce((n,r)=>n+Number(r.fee_amount||0),0);

 if(!authenticated)return <><SiteHeader ctaLabel="Back to site" ctaHref="/"/><main className={styles.loginPage}><div className={styles.loginShell}><div className={styles.loginMark}>VSI</div><p className="kicker">ADMIN ACCESS</p><h1>Event Registrations</h1><p>Sign in to review and manage participant registrations.</p><form onSubmit={login} className={styles.loginForm}><label htmlFor="admin-password">Admin password</label><input id="admin-password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/>{loginError&&<div className={styles.error}>{loginError}</div>}<button type="submit">Sign in <span>↗</span></button></form></div></main><SiteFooter/></>;

 return <><SiteHeader ctaLabel="Public site" ctaHref="/"/><main className={styles.page}><div className={styles.shell}>
  <div className={styles.topline}><span>VSI IMS <b>/</b> Event Registrations</span><div><span className={styles.connected}><i/> Connected</span><button onClick={()=>loadRegistrations(selectedId)}>Refresh ↻</button><button onClick={logout}>Log out ↪</button></div></div>
  <section className={styles.hero}><div><p className="kicker light">EVENTS &amp; ENGAGEMENT</p><h1>Event Registrations</h1><p>Review, search, edit and manage participants registered through VSI Events.</p></div><div className={styles.heroOrb}>V</div></section>
  {error&&<div className={styles.error}>{error}</div>}{notice&&<div style={{marginBottom:14,padding:"14px 16px",borderRadius:12,background:"#edf8f3",color:"#137a50",border:"1px solid #ccebdd"}}>{notice}</div>}
  <section className={styles.stats} style={{gridTemplateColumns:"repeat(7,minmax(0,1fr))",marginBottom:18}}>
   <div className={`${styles.stat} ${styles.statNavy}`} style={{cursor:"default"}}><span className={styles.statIcon}>#</span><small>SELECTED EVENT</small><strong style={{fontSize:24,lineHeight:1.15}}>{event?.title||"—"}</strong><b>{event?.event_date?String(event.event_date).slice(0,10):"Select an event"}</b><em>{event?.venue||event?.location||"Venue not provided"}</em></div>
   <div className={`${styles.stat} ${styles.statBlue}`} style={{cursor:"default"}}><span className={styles.statIcon}>+</span><small>REGISTRATIONS</small><strong>{registrations.length}</strong><b>Participants registered</b><em>For the selected event</em></div>\n   <div className={`${styles.stat} ${styles.statBlue}`} style={{cursor:"default"}}><span className={styles.statIcon}>✓</span><small>PAID</small><strong>{paidRegistrations.length}</strong><b>Payment confirmed</b><em>{registrations.length-paidRegistrations.length} not yet paid</em></div>\n   <div className={`${styles.stat} ${styles.statYellow}`} style={{cursor:"default"}}><span className={styles.statIcon}>!</span><small>REGRETS</small><strong>{regrets.length}</strong><b>Will not attend</b><em>{expectedAttendees.length} expected attendees</em></div>
   <div className={`${styles.stat} ${styles.statYellow}`} style={{cursor:"default"}}><span className={styles.statIcon}>ZK</span><small>EVENT FINANCES</small><strong style={{fontSize:28}}>ZMW {totalAmount.toLocaleString()}</strong><b>Total registration value</b><em>Full value of all registrations</em></div>
   <div className={`${styles.stat} ${styles.statBlue}`} style={{cursor:"default"}}><span className={styles.statIcon}>✓</span><small>AMOUNT RECEIVED</small><strong style={{fontSize:28}}>ZMW {paidAmount.toLocaleString()}</strong><b>Payments confirmed</b><em>{paidRegistrations.length} paid participant{paidRegistrations.length===1?"":"s"}</em></div>
   <div className={`${styles.stat} ${styles.statYellow}`} style={{cursor:"default"}}><span className={styles.statIcon}>W</span><small>AMOUNT WAIVED</small><strong style={{fontSize:28}}>ZMW {waivedAmount.toLocaleString()}</strong><b>Complimentary / waived</b><em>Excluded from collections</em></div>
   <div className={`${styles.stat} ${styles.statNavy}`} style={{cursor:"default"}}><span className={styles.statIcon}>ZK</span><small>OUTSTANDING</small><strong style={{fontSize:28}}>ZMW {outstandingAmount.toLocaleString()}</strong><b>Balance remaining</b><em>{registrations.filter(r=>r.payment_status==="unpaid").length} unpaid participant{registrations.filter(r=>r.payment_status==="unpaid").length===1?"":"s"}</em></div>
  </section>
  <section className={styles.registerPanel}>
   <div className={styles.registerHeader}><div><p className="kicker">EVENT REGISTER</p><h2>Participant registrations</h2></div><strong>{filtered.length} shown</strong></div>
   <div className={styles.toolbar}><div className={styles.searchWrap}><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email, phone, organisation..."/></div><select value={selectedId} onChange={e=>{setSelectedId(e.target.value);setSelected(null);setSearch("")}}><option value="">Select an event</option>{events.map(e=><option key={e.id} value={e.id}>{e.title} · {e.event_date?String(e.event_date).slice(0,10):"No date"}</option>)}</select><button className={styles.clearButton} onClick={()=>{setSearch("");setSelected(null)}}>Clear</button></div>
   {loading?<div className={styles.empty}>Loading event register<span className={styles.loadingDots}>...</span></div>:!selectedId?<div className={styles.empty}>Select an event to view its register.</div>:filtered.length===0?<div className={styles.empty}>No registrations found for this event.</div>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1120}}><thead><tr><th style={th}>#</th><th style={th}>Participant</th><th style={th}>Contact</th><th style={th}>Organisation</th><th style={th}>Gender / Disability</th><th style={th}>Location</th><th style={th}>Fee</th><th style={th}>Payment</th><th style={th}>Attendance</th><th style={th}>Registered</th><th style={th}>Actions</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={r.id}><td style={td}>{i+1}</td><td style={td}><strong style={{color:"#102a43",fontSize:14}}>{r.full_name}</strong><div style={{color:"#627d98",marginTop:4,fontSize:12}}>{r.designation||"—"}</div></td><td style={td}>{r.email||"—"}<br/>{r.phone||"—"}</td><td style={td}>{r.organization||"—"}</td><td style={td}>{r.gender||"—"}<br/>{r.disability||"—"}</td><td style={td}>{[r.province,r.district,r.residential_area].filter(Boolean).join(" · ")||"—"}</td><td style={td}><strong style={{color:"#0b3052"}}>ZMW {Number(r.fee_amount||0).toLocaleString()}</strong><div style={{color:"#829ab1",fontSize:11,marginTop:3}}>{r.fee_label||"Registered"}</div></td><td style={td}><strong style={{color:r.payment_status==="paid"?"#137a50":"#a66a00"}}>{r.payment_status==="paid"?"Paid":r.payment_status==="waived"?"Waived":"Unpaid"}</strong></td><td style={td}><strong style={{color:r.attendance_status==="regrets"?"#a32d2d":"#137a50"}}>{r.attendance_status==="regrets"?"Regrets":"Expected"}</strong></td><td style={td}>{r.created_at?new Date(r.created_at).toLocaleString("en-GB"):"—"}</td><td style={{...td,whiteSpace:"nowrap"}}><button onClick={()=>setSelected({...r})} style={{...action,background:"#edf2f7",color:"#0b3052",marginRight:7}}>Edit</button><button onClick={()=>remove(r.id)} style={{...action,background:"#fff1f0",color:"#a32d2d",border:"1px solid #f1b8b8"}}>Delete</button></td></tr>)}</tbody></table></div>}
  </section>
  {selected&&<section className={styles.editPanel} style={{marginTop:18}}><div className={styles.actionRow}><div><span className={styles.kickerSmall}>EDIT REGISTRATION</span><strong>{selected.full_name}</strong></div><div><button onClick={()=>remove(selected.id)} className={styles.dangerButton}>Delete</button><button onClick={()=>setSelected(null)} className={styles.secondaryButton}>Cancel</button><button onClick={save} disabled={saving} className={styles.saveReview}>{saving?"Saving...":"Save changes"}</button></div></div><div className={styles.editGrid}>{[["full_name","Full name"],["designation","Designation"],["email","Email"],["phone","Phone"],["organization","Organisation"],["gender","Gender"],["disability","Disability"],["province","Province"],["district","District"],["residential_area","Residential area"]].map(([key,label])=><label key={key}>{label}<input style={inputStyle} value={selected[key]||""} onChange={e=>setSelected(x=>({...x,[key]:e.target.value}))}/></label>)}</div><div className={styles.editGrid} style={{marginTop:16}}><label>Payment status<select style={inputStyle} value={selected.payment_status||"unpaid"} onChange={e=>setSelected(x=>({...x,payment_status:e.target.value}))}><option value="unpaid">Unpaid</option><option value="paid">Paid</option><option value="waived">Waived / Complimentary</option></select></label><label>Attendance status<select style={inputStyle} value={selected.attendance_status||"registered"} onChange={e=>setSelected(x=>({...x,attendance_status:e.target.value}))}><option value="registered">Expected to attend</option><option value="regrets">Regrets / Not attending</option></select></label></div></section>}
 </div></main><SiteFooter/></>;
}
