"use client";
import {useEffect,useMemo,useState} from "react";
import {SiteFooter,SiteHeader} from "../../components/SiteChrome";

const inputStyle={width:"100%",boxSizing:"border-box",padding:"10px 12px",border:"1px solid #dbe3ec",borderRadius:10,fontSize:14};
const th={textAlign:"left",padding:"12px 10px",fontSize:12,color:"#64748b",borderBottom:"1px solid #e5e7eb",whiteSpace:"nowrap"};
const td={padding:"12px 10px",borderBottom:"1px solid #eef2f7",fontSize:13,verticalAlign:"top"};

export default function EventRegistrationsAdmin(){
 const[authenticated,setAuthenticated]=useState(false),[password,setPassword]=useState(""),[loginError,setLoginError]=useState("");
 const[events,setEvents]=useState([]),[selectedId,setSelectedId]=useState(""),[registrations,setRegistrations]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState("");
 const[selected,setSelected]=useState(null),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");

 async function loadEvents(){
  setLoading(true);setError("");
  try{const r=await fetch("/api/admin/events",{cache:"no-store"});const d=await r.json();if(r.status===401){setAuthenticated(false);return}if(!r.ok)throw Error(d.error||"Unable to load events.");setAuthenticated(true);const list=d.events||[];setEvents(list);if(!selectedId&&list.length)setSelectedId(String(list[0].id));}
  catch(e){setError(e.message)}finally{setLoading(false)}
 }
 async function loadRegistrations(id){
  if(!id){setRegistrations([]);return}setLoading(true);setError("");
  try{const r=await fetch(`/api/admin/event-registrations?event_id=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json();if(r.status===401){setAuthenticated(false);return}if(!r.ok)throw Error(d.error||"Unable to load registrations.");setRegistrations(d.registrations||[])}catch(e){setError(e.message)}finally{setLoading(false)}
 }
 useEffect(()=>{loadEvents()},[]);
 useEffect(()=>{if(authenticated&&selectedId)loadRegistrations(selectedId)},[selectedId,authenticated]);
 async function login(e){e.preventDefault();setLoginError("");const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const d=await r.json();if(!r.ok){setLoginError(d.error||"Unable to sign in.");return}setPassword("");await loadEvents()}
 async function logout(){await fetch("/api/admin/login",{method:"DELETE"});setAuthenticated(false);setEvents([]);setRegistrations([])}
 async function remove(id){if(!confirm("Delete this event registration permanently?"))return;const r=await fetch(`/api/admin/event-registrations?id=${id}`,{method:"DELETE"});const d=await r.json();if(!r.ok){setError(d.error||"Unable to delete registration.");return}setRegistrations(xs=>xs.filter(x=>x.id!==id));setNotice("Registration deleted.");setSelected(null)}
 async function save(){if(!selected)return;setSaving(true);setError("");setNotice("");try{const r=await fetch("/api/admin/event-registrations",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(selected)});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to save registration.");setRegistrations(xs=>xs.map(x=>x.id===d.registration.id?d.registration:x));setSelected(d.registration);setNotice("Registration updated successfully.")}catch(e){setError(e.message)}finally{setSaving(false)}}
 const event=events.find(x=>String(x.id)===String(selectedId));
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return registrations;return registrations.filter(r=>[r.full_name,r.email,r.phone,r.organization,r.province,r.district,r.designation].some(v=>String(v||"").toLowerCase().includes(q)))},[registrations,search]);
 const totalAmount=registrations.reduce((n,r)=>n+Number(r.fee_amount||0),0);

 if(!authenticated)return <><SiteHeader ctaLabel="Back to site" ctaHref="/"/><main style={{minHeight:"70vh",display:"grid",placeItems:"center",padding:"60px 20px",background:"#f6f9fc"}}><div style={{width:"100%",maxWidth:460,background:"#fff",border:"1px solid #e3eaf1",borderRadius:20,padding:32,boxShadow:"0 18px 50px rgba(7,61,133,.08)"}}><div style={{fontWeight:900,color:"#073d85",fontSize:28}}>VSI</div><p style={{fontSize:12,fontWeight:800,letterSpacing:1.5,color:"#718096"}}>ADMIN ACCESS</p><h1 style={{margin:"8px 0"}}>Event Registrations</h1><p style={{color:"#64748b"}}>Sign in to view and manage participant registrations.</p><form onSubmit={login}><label style={{display:"block",fontWeight:700,fontSize:13}}>Admin password<input style={{...inputStyle,marginTop:7}} type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{loginError&&<p style={{color:"#b42318",fontSize:13}}>{loginError}</p>}<button style={{marginTop:16,width:"100%",padding:"12px 16px",border:0,borderRadius:10,background:"#073d85",color:"white",fontWeight:800,cursor:"pointer"}}>Sign in ↗</button></form></div></main><SiteFooter/></>;

 return <><SiteHeader ctaLabel="Public site" ctaHref="/"/><main style={{background:"#f6f9fc",minHeight:"80vh",padding:"28px 20px 60px"}}><div style={{maxWidth:1400,margin:"0 auto"}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,flexWrap:"wrap",marginBottom:22}}><div><p style={{margin:0,fontSize:12,fontWeight:800,letterSpacing:1.5,color:"#64748b"}}>VSI IMS / EVENT REGISTER</p><h1 style={{margin:"5px 0",color:"#0f2740"}}>Event Registrations</h1><p style={{margin:0,color:"#64748b"}}>View, search, edit and manage registrations submitted through VSI Events.</p></div><div style={{display:"flex",gap:8}}><button onClick={()=>loadRegistrations(selectedId)} style={{padding:"10px 14px",border:"1px solid #d5dee8",borderRadius:10,background:"#fff",fontWeight:700}}>Refresh ↻</button><button onClick={logout} style={{padding:"10px 14px",border:0,borderRadius:10,background:"#0f2740",color:"#fff",fontWeight:700}}>Log out ↪</button></div></div>
  {error&&<div style={{padding:12,borderRadius:10,background:"#fff1f0",color:"#b42318",marginBottom:14}}>{error}</div>}{notice&&<div style={{padding:12,borderRadius:10,background:"#effaf3",color:"#176b3a",marginBottom:14}}>{notice}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:12,marginBottom:18}}><div style={{background:"#fff",border:"1px solid #e1e8ef",borderRadius:14,padding:18}}><div style={{fontSize:12,fontWeight:800,color:"#64748b"}}>SELECTED EVENT</div><strong style={{display:"block",marginTop:6,fontSize:18}}>{event?.title||"—"}</strong></div><div style={{background:"#fff",border:"1px solid #e1e8ef",borderRadius:14,padding:18}}><div style={{fontSize:12,fontWeight:800,color:"#64748b"}}>REGISTRATIONS</div><strong style={{display:"block",marginTop:6,fontSize:26}}>{registrations.length}</strong></div><div style={{background:"#fff",border:"1px solid #e1e8ef",borderRadius:14,padding:18}}><div style={{fontSize:12,fontWeight:800,color:"#64748b"}}>FEES RECORDED</div><strong style={{display:"block",marginTop:6,fontSize:26}}>ZMW {totalAmount.toLocaleString()}</strong></div></section>
  <section style={{background:"#fff",border:"1px solid #e1e8ef",borderRadius:18,overflow:"hidden"}}><div style={{padding:18,borderBottom:"1px solid #e5e7eb",display:"flex",gap:12,alignItems:"center",flexWrap:"wrap"}}><select value={selectedId} onChange={e=>{setSelectedId(e.target.value);setSelected(null);setSearch("")}} style={{...inputStyle,maxWidth:480}}><option value="">Select an event</option>{events.map(e=><option key={e.id} value={e.id}>{e.title} · {e.event_date?String(e.event_date).slice(0,10):"No date"}</option>)}</select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email, phone, organisation..." style={{...inputStyle,maxWidth:420}}/></div>
   {loading?<div style={{padding:40,textAlign:"center",color:"#64748b"}}>Loading registrations...</div>:!selectedId?<div style={{padding:40,textAlign:"center",color:"#64748b"}}>Select an event to view its register.</div>:filtered.length===0?<div style={{padding:40,textAlign:"center",color:"#64748b"}}>No registrations found for this event.</div>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1050}}><thead><tr><th style={th}>#</th><th style={th}>Participant</th><th style={th}>Contact</th><th style={th}>Organisation</th><th style={th}>Gender / Disability</th><th style={th}>Province / District</th><th style={th}>Fee</th><th style={th}>Registered</th><th style={th}>Action</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={r.id}><td style={td}>{i+1}</td><td style={td}><strong>{r.full_name}</strong><div style={{color:"#64748b",marginTop:3}}>{r.designation}</div></td><td style={td}>{r.email}<br/>{r.phone}</td><td style={td}>{r.organization||"—"}</td><td style={td}>{r.gender}<br/>{r.disability}</td><td style={td}>{r.province}<br/>{r.district}</td><td style={td}>ZMW {Number(r.fee_amount||0).toLocaleString()}<br/><span style={{color:"#64748b"}}>{r.fee_label}</span></td><td style={td}>{r.created_at?new Date(r.created_at).toLocaleString("en-GB"):"—"}</td><td style={td}><button onClick={()=>setSelected({...r})} style={{padding:"7px 10px",border:"1px solid #d5dee8",borderRadius:8,background:"#fff",fontWeight:700}}>Edit</button></td></tr>)}</tbody></table></div>}
  </section>
  {selected&&<section style={{marginTop:18,background:"#fff",border:"1px solid #e1e8ef",borderRadius:18,padding:20}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><p style={{margin:0,fontSize:12,fontWeight:800,letterSpacing:1.2,color:"#64748b"}}>EDIT REGISTRATION</p><h2 style={{margin:"5px 0"}}>{selected.full_name}</h2></div><div style={{display:"flex",gap:8}}><button onClick={()=>remove(selected.id)} style={{padding:"9px 13px",border:"1px solid #f0b4b0",borderRadius:9,background:"#fff5f4",color:"#b42318",fontWeight:700}}>Delete</button><button onClick={()=>setSelected(null)} style={{padding:"9px 13px",border:"1px solid #d5dee8",borderRadius:9,background:"#fff",fontWeight:700}}>Cancel</button><button onClick={save} disabled={saving} style={{padding:"9px 13px",border:0,borderRadius:9,background:"#073d85",color:"#fff",fontWeight:800}}>{saving?"Saving...":"Save changes"}</button></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:14,marginTop:18}}>{[["full_name","Full name"],["designation","Designation"],["email","Email"],["phone","Phone"],["organization","Organisation"],["gender","Gender"],["disability","Disability"],["province","Province"],["district","District"],["residential_area","Residential area"]].map(([key,label])=><label key={key} style={{fontSize:12,fontWeight:800,color:"#475569"}}>{label}<input style={{...inputStyle,marginTop:6}} value={selected[key]||""} onChange={e=>setSelected(x=>({...x,[key]:e.target.value}))}/></label>)}</div></section>}
 </div></main><SiteFooter/></>;
}
