"use client";

import { useState } from "react";
import styles from "./apply.module.css";

const initialForm={fullName:"",age:"",nationality:"",gender:"",faith:"",email:"",phone:"",province:"",district:"",constituency:"",ward:"",location:"",currentOccupation:"",education:"",category:"",skills:"",availability:"",hoursPerWeek:"6",motivation:"",volunteeringElsewhere:"no",otherVolunteeringDetails:"",pastVolunteerPositions:"",referenceName:"",referenceOrganization:"",referencePhone:"",referenceEmail:"",criminalConviction:"no",criminalOffenceDetails:"",disability:"no",disabilityCertificate:"",disabilityCertificateName:"",profilePicture:"",emergencyName:"",emergencyPhone:"",consent:false};
const categories=["Programme volunteer","School-based volunteer","Community volunteer","Youth volunteer","Technical & professional","Short-term / event volunteer"];
const provinces=["Central","Copperbelt","Eastern","Luapula","Lusaka","Muchinga","Northern","North-Western","Southern","Western"];
const genders=["Female","Male","Prefer not to say","Other"];
const faiths=["Christianity","Islam","Hinduism","Traditional / Indigenous faith","Other","Prefer not to say"];
const hours=["1","2","3","4","5","6","7","8","9","10","12","14","16","20","24","40"];
const compressImage=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=700,s=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement("canvas");c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext("2d").drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL("image/jpeg",.78));};img.onerror=reject;img.src=r.result;};r.onerror=reject;r.readAsDataURL(file);});
const readFile=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});

export default function VolunteerApplication(){
 const [form,setForm]=useState(initialForm),[submitted,setSubmitted]=useState(false),[error,setError]=useState(""),[saving,setSaving]=useState(false),[photoBusy,setPhotoBusy]=useState(false),[certificateBusy,setCertificateBusy]=useState(false);
 const updateField=e=>{const{name,value,type,checked}=e.target;setForm(c=>({...c,[name]:type==="checkbox"?checked:value}));};
 async function handlePhoto(e){const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith("image/")){setError("Please choose an image file.");return;}setPhotoBusy(true);setError("");try{const data=await compressImage(f);if(data.length>1200000)throw new Error("Please choose a smaller profile image.");setForm(c=>({...c,profilePicture:data}));}catch(err){setError(err.message||"Unable to process the photo.");}finally{setPhotoBusy(false);}}
 async function handleCertificate(e){const f=e.target.files?.[0];if(!f)return;const allowed=f.type==="application/pdf"||f.type.startsWith("image/");if(!allowed){setError("Please upload a PDF or image certificate.");return;}if(f.size>2000000){setError("Please choose a certificate file no larger than 2 MB.");return;}setCertificateBusy(true);setError("");try{const data=await readFile(f);setForm(c=>({...c,disabilityCertificate:data,disabilityCertificateName:f.name}));}catch(err){setError("Unable to read the certificate.");}finally{setCertificateBusy(false);}}
 async function handleSubmit(e){e.preventDefault();setError("");setSaving(true);try{const r=await fetch("/api/volunteers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,volunteeringElsewhere:form.volunteeringElsewhere==="yes",criminalConviction:form.criminalConviction==="yes",disability:form.disability==="yes"})});const d=await r.json();if(!r.ok)throw new Error(d.detail||d.error||"Unable to submit application.");setSubmitted(true);}catch(err){setError(err.message);}finally{setSaving(false);}}
 if(submitted)return <main className={styles.page}><div className={styles.successCard}><span className={styles.successMark}>✓</span><p className="kicker">APPLICATION RECEIVED</p><h1>Thank you for your interest in VSI.</h1><p>Your volunteer application has been submitted successfully. The VSI team can now review your information and contact you about suitable opportunities.</p><a className={styles.button} href="/volunteer">Return to volunteering</a></div></main>;
 return <main className={styles.page}><div className={styles.shell}><a className={styles.back} href="/volunteer">← Back to volunteer information</a><header className={styles.header}><p className="kicker">VSI VOLUNTEER APPLICATION</p><h1>Tell us how you can contribute.</h1><p>Complete this application so VSI can understand your background, experience, availability and support needs.</p></header><form className={styles.form} onSubmit={handleSubmit}>
 <section className={styles.section}><div className={styles.sectionIntro}><span>01</span><div><h2>Your details</h2><p>Basic information for your volunteer record.</p></div></div><div className={styles.grid}><label>Full name *<input name="fullName" value={form.fullName} onChange={updateField} required /></label><label>Age *<input type="number" name="age" value={form.age} onChange={updateField} required min="1" max="120" /></label><label>Nationality *<input name="nationality" value={form.nationality} onChange={updateField} required /></label><label>Gender *<select name="gender" value={form.gender} onChange={updateField} required><option value="">Select gender</option>{genders.map(x=><option key={x}>{x}</option>)}</select></label><label>Faith / religion *<select name="faith" value={form.faith} onChange={updateField} required><option value="">Select faith</option>{faiths.map(x=><option key={x}>{x}</option>)}</select></label><label>Email address *<input type="email" name="email" value={form.email} onChange={updateField} required /></label><label>Phone number *<input type="tel" name="phone" value={form.phone} onChange={updateField} required /></label><label>Current occupation / status *<input name="currentOccupation" value={form.currentOccupation} onChange={updateField} required placeholder="e.g. Student, teacher, entrepreneur" /></label><label>Education / qualification<input name="education" value={form.education} onChange={updateField} /></label><label>Profile picture *<input type="file" accept="image/*" onChange={handlePhoto} required />{photoBusy&&<small>Preparing photo…</small>}{form.profilePicture&&<small>Photo ready ✓</small>}</label></div></section>
 <section className={styles.section}><div className={styles.sectionIntro}><span>02</span><div><h2>Location</h2><p>Provide your current residential/community location.</p></div></div><div className={styles.grid}><label>Province *<select name="province" value={form.province} onChange={updateField} required><option value="">Select province</option>{provinces.map(p=><option key={p}>{p}</option>)}</select></label><label>District *<input name="district" value={form.district} onChange={updateField} required /></label><label>Constituency *<input name="constituency" value={form.constituency} onChange={updateField} required /></label><label>Ward *<input name="ward" value={form.ward} onChange={updateField} required /></label></div></section>
 <section className={styles.section}><div className={styles.sectionIntro}><span>03</span><div><h2>How you want to serve</h2><p>Six hours per week is VSI's recommended volunteer commitment.</p></div></div><div className={styles.grid}><label>Volunteer category *<select name="category" value={form.category} onChange={updateField} required><option value="">Select a category</option>{categories.map(i=><option key={i}>{i}</option>)}</select></label><label>Expected hours per week *<select name="hoursPerWeek" value={form.hoursPerWeek} onChange={updateField} required>{hours.map(h=><option key={h} value={h}>{h} hour{h==="1"?"":"s"} per week{h==="6"?" — VSI recommended":""}</option>)}</select></label><label>Availability details *<input name="availability" value={form.availability} onChange={updateField} required placeholder="e.g. Weekends, weekday afternoons" /></label><label className={styles.full}>Skills, experience or qualifications *<textarea name="skills" value={form.skills} onChange={updateField} required rows="4" /></label><label className={styles.full}>Why would you like to volunteer with VSI? *<textarea name="motivation" value={form.motivation} onChange={updateField} required rows="4" /></label></div></section>
 <section className={styles.section}><div className={styles.sectionIntro}><span>04</span><div><h2>Volunteer experience &amp; references</h2><p>Tell us about current and past service and provide a reference we can verify.</p></div></div><div className={styles.grid}><label>Currently volunteering elsewhere? *<select name="volunteeringElsewhere" value={form.volunteeringElsewhere} onChange={updateField}><option value="no">No</option><option value="yes">Yes</option></select></label>{form.volunteeringElsewhere==="yes"&&<label>Current organisation / role details *<input name="otherVolunteeringDetails" value={form.otherVolunteeringDetails} onChange={updateField} required /></label>}<label className={styles.full}>Past volunteer positions / organisations<textarea name="pastVolunteerPositions" value={form.pastVolunteerPositions} onChange={updateField} rows="4" placeholder="Organisation, role, period and key responsibilities." /></label><label>Reference name *<input name="referenceName" value={form.referenceName} onChange={updateField} required /></label><label>Reference organisation *<input name="referenceOrganization" value={form.referenceOrganization} onChange={updateField} required /></label><label>Reference phone *<input type="tel" name="referencePhone" value={form.referencePhone} onChange={updateField} required /></label><label>Reference email *<input type="email" name="referenceEmail" value={form.referenceEmail} onChange={updateField} required /></label></div></section>
 <section className={styles.section}><div className={styles.sectionIntro}><span>05</span><div><h2>Safeguarding, disability &amp; disclosure</h2><p>These details are handled confidentially and used for appropriate safeguarding, verification and inclusion.</p></div></div><div className={styles.grid}><label>Do you have a disability? *<select name="disability" value={form.disability} onChange={updateField}><option value="no">No</option><option value="yes">Yes</option></select></label>{form.disability==="yes"&&<label>Disability certificate *<input type="file" accept="application/pdf,image/*" onChange={handleCertificate} required />{certificateBusy&&<small>Preparing certificate…</small>}{form.disabilityCertificate&&<small>{form.disabilityCertificateName} ✓</small>}</label>}{form.disability==="yes"&&<p className={styles.notice}>Please provide a disability certificate issued by the Ministry of Community Development and Social Services or the Zambia Agency for Persons with Disabilities (ZAPD).</p>}<label>To the best of your knowledge, have you ever been convicted of a criminal offence? *<select name="criminalConviction" value={form.criminalConviction} onChange={updateField}><option value="no">No</option><option value="yes">Yes</option></select></label>{form.criminalConviction==="yes"&&<label className={styles.full}>Details of the conviction *<textarea name="criminalOffenceDetails" value={form.criminalOffenceDetails} onChange={updateField} required rows="5" /></label>}</div></section>
 <section className={styles.section}><div className={styles.sectionIntro}><span>06</span><div><h2>Emergency contact</h2><p>For volunteer safety and appropriate support.</p></div></div><div className={styles.grid}><label>Contact name *<input name="emergencyName" value={form.emergencyName} onChange={updateField} required /></label><label>Contact phone *<input type="tel" name="emergencyPhone" value={form.emergencyPhone} onChange={updateField} required /></label></div></section>
 <section className={styles.consent}><label className={styles.checkbox}><input type="checkbox" name="consent" checked={form.consent} onChange={updateField} required /><span>I confirm that the information I have provided is accurate and I agree to VSI reviewing it for volunteer opportunities and appropriate verification. *</span></label><p>Volunteer roles may require induction, training, supervision and additional safeguarding or screening depending on the assignment.</p></section>{error&&<div className={styles.error}>{error}</div>}<button className={styles.button} type="submit" disabled={saving||photoBusy||certificateBusy}>{saving?"Submitting application…":<>Submit volunteer application <span aria-hidden="true">→</span></>}</button>
 </form></div></main>;
}
