import { NextResponse } from "next/server";
import { ensureNewsTable, pool } from "../../../../lib/db";
import { isAdminAuthenticated } from "../../../../lib/admin-auth";

const unauthorized=()=>NextResponse.json({error:"Admin authentication required."},{status:401});
const clean=v=>typeof v==="string"?v.trim():"";
function makeSlug(value){return clean(value).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,90)||`news-${Date.now()}`;}
async function uniqueSlug(title,id=null){const base=makeSlug(title);let slug=base;let n=2;while(true){const q=id?await pool.query("SELECT id FROM news_articles WHERE slug=$1 AND id<>$2 LIMIT 1",[slug,id]):await pool.query("SELECT id FROM news_articles WHERE slug=$1 LIMIT 1",[slug]);if(!q.rowCount)return slug;slug=`${base}-${n++}`;}}

export async function GET(request){if(!isAdminAuthenticated(request))return unauthorized();try{await ensureNewsTable();const r=await pool.query("SELECT * FROM news_articles ORDER BY CASE WHEN status='draft' THEN 0 WHEN status='published' THEN 1 ELSE 2 END, COALESCE(published_at,created_at) DESC,id DESC");return NextResponse.json({articles:r.rows});}catch(e){console.error(e);return NextResponse.json({error:"Unable to load news register."},{status:500});}}

export async function POST(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();const title=clean(b.title),category=clean(b.category),excerpt=clean(b.excerpt),content=clean(b.content);if(!title||!category||!excerpt||!content)return NextResponse.json({error:"Title, category, summary and full story are required."},{status:400});await ensureNewsTable();const status=["draft","published","archived"].includes(b.status)?b.status:"draft";const slug=await uniqueSlug(title);const publishedAt=status==='published'?(b.published_at||new Date().toISOString()):null;const r=await pool.query(`INSERT INTO news_articles (title,slug,category,excerpt,content,featured_image,author,directorate,programme,project,status,featured,published_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[title,slug,category,excerpt,content,clean(b.featured_image)||null,clean(b.author)||null,clean(b.directorate)||null,clean(b.programme)||null,clean(b.project)||null,status,!!b.featured,publishedAt]);return NextResponse.json({ok:true,article:r.rows[0]},{status:201});}catch(e){console.error(e);return NextResponse.json({error:"Unable to create news story."},{status:500});}}

export async function PUT(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();if(!b.id)return NextResponse.json({error:"News story ID is required."},{status:400});const title=clean(b.title),category=clean(b.category),excerpt=clean(b.excerpt),content=clean(b.content);if(!title||!category||!excerpt||!content)return NextResponse.json({error:"Title, category, summary and full story are required."},{status:400});await ensureNewsTable();const status=["draft","published","archived"].includes(b.status)?b.status:"draft";const slug=await uniqueSlug(title,b.id);const publishedAt=status==='published'?(b.published_at||new Date().toISOString()):null;const r=await pool.query(`UPDATE news_articles SET title=$1,slug=$2,category=$3,excerpt=$4,content=$5,featured_image=$6,author=$7,directorate=$8,programme=$9,project=$10,status=$11,featured=$12,published_at=$13,updated_at=NOW() WHERE id=$14 RETURNING *`,[title,slug,category,excerpt,content,clean(b.featured_image)||null,clean(b.author)||null,clean(b.directorate)||null,clean(b.programme)||null,clean(b.project)||null,status,!!b.featured,publishedAt,b.id]);if(!r.rowCount)return NextResponse.json({error:"News story not found."},{status:404});return NextResponse.json({ok:true,article:r.rows[0]});}catch(e){console.error(e);return NextResponse.json({error:"Unable to update news story."},{status:500});}}

export async function DELETE(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();if(!b.id)return NextResponse.json({error:"News story ID is required."},{status:400});await ensureNewsTable();const r=await pool.query("DELETE FROM news_articles WHERE id=$1 RETURNING id",[b.id]);if(!r.rowCount)return NextResponse.json({error:"News story not found."},{status:404});return NextResponse.json({ok:true,id:r.rows[0].id});}catch(e){console.error(e);return NextResponse.json({error:"Unable to delete news story."},{status:500});}}
