import Image from "next/image";
import Link from "next/link";
import {SiteFooter,SiteHeader} from "../components/SiteChrome";
import styles from "./events.module.css";

async function getEvents(){try{const r=await fetch("https://www.vsizambia.org/api/events",{cache:"no-store"});if(!r.ok)return [];const d=await r.json();return Array.isArray(d.events)?d.events:[];}catch{return [];}}
function dateParts(value){const d=new Date(`${String(value).slice(0,10)}T00:00:00`);return {day:d.toLocaleDateString("en-GB",{day:"2-digit"}),month:d.toLocaleDateString("en-GB",{month:"short"}).toUpperCase(),full:d.toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})};}
function timeRange(a){if(!a.start_time)return "";const f=v=>new Date(`1970-01-01T${String(v).slice(0,8)}`).toLocaleTimeString("en-GB",{hour:"numeric",minute:"2-digit"});return a.end_time?`${f(a.start_time)} – ${f(a.end_time)}`:f(a.start_time);}

export default async function EventsPage(){const events=await getEvents();const featured=events.filter(x=>x.featured)[0]||events[0];const rest=events.filter(x=>x.id!==featured?.id);return <><SiteHeader/><main className={styles.page}><section className={styles.hero}><div className={styles.heroInner}><p className="kicker">VSI EVENTS</p><h1>Connect, learn, participate.</h1><p>Discover upcoming VSI conferences, workshops, dialogues, trainings and community engagements.</p></div></section><section className={styles.shell}>{events.length===0?<div className={styles.empty}><p className="kicker">UPCOMING EVENTS</p><h2>No upcoming events just yet.</h2><p>Check back soon for the next VSI event.</p></div>:<><div className={styles.sectionHead}><div><p className="kicker">UPCOMING EVENTS</p><h2>What’s happening at VSI</h2></div></div>{featured&&<Link href={`/events/${featured.slug}`} className={styles.featured}><div className={styles.featuredImage}>{featured.featured_image?<Image src={featured.featured_image} alt="" fill sizes="(max-width: 800px) 100vw, 55vw"/>:<div className={styles.imageFallback}>VSI</div>}</div><div className={styles.featuredBody}><div className={styles.dateBox}><strong>{dateParts(featured.event_date).day}</strong><span>{dateParts(featured.event_date).month}</span></div><div><span className={styles.category}>{featured.category}</span><h3>{featured.title}</h3><p>{featured.summary}</p><div className={styles.meta}>{dateParts(featured.event_date).full}{timeRange(featured)&&` · ${timeRange(featured)}`}{(featured.venue||featured.location)&&` · ${featured.venue||featured.location}`}</div><span className={styles.read}>View event ↗</span></div></div></Link>}{rest.length>0&&<div className={styles.grid}>{rest.map(a=>{const dp=dateParts(a.event_date);return <Link href={`/events/${a.slug}`} className={styles.card} key={a.id}><div className={styles.cardImage}>{a.featured_image?<Image src={a.featured_image} alt="" fill sizes="(max-width: 800px) 100vw, 33vw"/>:<div className={styles.imageFallback}>VSI</div>}</div><div className={styles.cardBody}><div className={styles.cardTop}><span className={styles.dateMini}><b>{dp.day}</b>{dp.month}</span><span className={styles.category}>{a.category}</span></div><h3>{a.title}</h3><p>{a.summary}</p><div className={styles.meta}>{dp.full}{(a.venue||a.location)&&` · ${a.venue||a.location}`}</div></div></Link>})}</div>}</>}</section></main><SiteFooter/></>}
