import Image from "next/image";
import Link from "next/link";
import {SiteFooter,SiteHeader} from "../../components/SiteChrome";
import styles from "../events.module.css";

async function getEvent(slug){try{const base=process.env.NEXT_PUBLIC_SITE_URL||"https://www.vsizambia.org";const r=await fetch(`${base}/api/events`,{next:{revalidate:60}});if(!r.ok)return null;const d=await r.json();return (d.events||[]).find(x=>x.slug===slug)||null;}catch{return null;}}
function fullDate(v){return new Date(`${String(v).slice(0,10)}T00:00:00`).toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"});}
function timeRange(a){if(!a.start_time)return "";const f=v=>new Date(`1970-01-01T${String(v).slice(0,8)}`).toLocaleTimeString("en-GB",{hour:"numeric",minute:"2-digit"});return a.end_time?`${f(a.start_time)} – ${f(a.end_time)}`:f(a.start_time);}

export default async function EventDetail({params}){const event=await getEvent(params.slug);if(!event)return <><SiteHeader/><main className={styles.shell}><div className={styles.empty}><p className="kicker">VSI EVENTS</p><h2>Event not found</h2><p>This event may have been removed or is no longer public.</p><Link href="/events">← Back to events</Link></div></main><SiteFooter/></>;return <><SiteHeader/><main className={styles.page}><article className={styles.shell}><Link href="/events" className={styles.read}>← Back to events</Link><p className="kicker" style={{marginTop:30}}>{event.category}</p><h1 style={{fontSize:"clamp(40px,6vw,72px)",lineHeight:1,letterSpacing:"-.04em",maxWidth:950,margin:"8px 0 20px"}}>{event.title}</h1><p style={{fontSize:19,lineHeight:1.6,maxWidth:800,color:"#5f6e83"}}>{event.summary}</p><div style={{margin:"32px 0",borderRadius:22,overflow:"hidden",background:"#e9eef6",position:"relative",minHeight:360}}>{event.featured_image?<Image src={event.featured_image} alt="" fill sizes="100vw" style={{objectFit:"cover"}}/>:<div className={styles.imageFallback}>VSI</div>}</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12,marginBottom:36}}><div style={{background:"#fff",border:"1px solid #e2e8f0",borderRadius:14,padding:16}}><b>Date</b><div>{fullDate(event.event_date)}</div></div>{timeRange(event)&&<div style={{background:"#fff",border:"1px solid #e2e8f0",borderRadius:14,padding:16}}><b>Time</b><div>{timeRange(event)}</div></div>} {(event.venue||event.location)&&<div style={{background:"#fff",border:"1px solid #e2e8f0",borderRadius:14,padding:16}}><b>Venue</b><div>{event.venue||event.location}{event.venue&&event.location?`, ${event.location}`:""}</div></div>}</div><div style={{maxWidth:820,fontSize:17,lineHeight:1.8,whiteSpace:"pre-wrap"}}>{event.content}</div>{(event.registration_url||event.contact)&&<div style={{marginTop:40,padding:24,borderRadius:18,background:"#073d85",color:"white"}}><h2 style={{marginTop:0}}>Join or enquire</h2>{event.contact&&<p>Contact: {event.contact}</p>}{event.registration_url&&<a href={event.registration_url} target="_blank" rel="noreferrer" style={{display:"inline-block",background:"#ffd21c",color:"#073d85",padding:"12px 18px",borderRadius:999,fontWeight:800,textDecoration:"none"}}>Register / learn more ↗</a>}</div>}</article></main><SiteFooter/></>}
