import Image from "next/image";
import { SiteHeader, SiteFooter } from "../components/SiteChrome";
import { ScrollStory } from "../components/ScrollStory";

export const metadata = { title: "Our Story", description: "Discover the story of Visionary Students Initiative, from a student idea to a growing movement for national development.", alternates: { canonical: "/story" }, openGraph: { title: "Our Story | Visionary Students Initiative", description: "Discover the story of Visionary Students Initiative, from a student idea to a growing movement for national development.", url: "https://www.vsizambia.org/story", images: [{ url: "/images/vsi story 1.jpg", alt: "The beginning of Visionary Students Initiative" }] }, twitter: { card: "summary_large_image", title: "Our Story | Visionary Students Initiative", description: "Discover the story of Visionary Students Initiative, from a student idea to a growing movement for national development.", images: ["/images/vsi story 1.jpg"] } };

const storyPanels = [
  { number: "01", title: "The beginning", text: "On 16 August 2018, at Cavendish University Zambia, VSI was born with a bold mission to redefine student participation in national development through community service.", image: "/images/vsi story 1.jpg", alt: "The beginning of Visionary Students Initiative" },
  { number: "02", title: "A room full of ideas", text: "The launch brought together voices from university management, human resources, public policy, poetry and climate advocacy — creating a foundation built on ideas, dialogue and possibility.", image: "/images/vsi story Room full of ideas.jpg", alt: "VSI story launch event" },
  { number: "03", title: "From club to NGO", text: "What began as a small club at CUZ has grown into an NGO contributing to national development through public policy advocacy, service provision and partnerships with government ministries, departments and agencies.", image: "/images/From Club to NGO.jpg", alt: "VSI growing from a student club into an NGO" },
  { number: "04", title: "Eight years and beyond", text: "Community service, volunteerism and humanitarian aid remain at the heart of the journey as VSI continues strengthening student participation in national development and stability.", image: "/images/vsi-parliament.jpg", alt: "VSI civic engagement at Parliament" },
];

export default function StoryPage() {
  return <main><SiteHeader /><section className="story-page-hero"><div className="section-shell story-page-hero-grid story-image-left"><div className="story-page-image"><Image src="/images/vsi-parliament.jpg" alt="VSI civic engagement at Parliament" fill priority sizes="(max-width: 900px) 100vw, 50vw" /></div><div><p className="kicker">THE #VSI STORY</p><h1>From a student idea to a growing movement for <em>national development.</em></h1><p>It started with a bold belief: students should not simply prepare for the future — they should have a meaningful role in shaping it.</p></div></div></section>
    <ScrollStory eyebrow="THE JOURNEY" title="A story built through people, service and participation." intro="Scroll through the moments that shaped VSI — from a student idea at Cavendish University Zambia to a growing movement for national development." panels={storyPanels} className="story-scroll" />
    <section className="story-next"><div className="section-shell"><p className="kicker light">KEEP THE STORY MOVING</p><h2>There is more to build — and more young people to bring to the table.</h2><a className="button button-yellow" href="/volunteer">Be part of VSI <span aria-hidden="true">↗</span></a></div></section><SiteFooter /></main>;
}
