export const PROGRAMME_REGISTER = [
  {directorate:"Programmes",programme:"Volunteer Management",project:"Volunteer Management Project",activities:["Volunteer recruitment","Volunteer induction","Volunteer training","Volunteer development","Volunteer deployment","Volunteer coordination","Volunteer recognition and retention"]},
  {directorate:"Programmes",programme:"Community Service and Volunteerism",project:"Community Service and Volunteerism Project",activities:["Community service","School/community outreach","On-campus training","Student volunteer activities","Community mobilisation","Community development activities","Social responsibility activities","Debate sessions"]},
  {directorate:"Programmes",programme:"Agriculture and Agro-processing",project:"Agriculture and Agro-processing Project",activities:["Agriculture skills training","Agro-processing training","Practical demonstrations","Entrepreneurship development","Value-chain development","Market linkage","Youth mentorship"]},
  {directorate:"Programmes",programme:"Technology and Innovation Entrepreneurship",project:"Technology and Innovation Entrepreneurship Project",activities:["Digital-skills training","Technology skills development","Innovation training","Entrepreneurship training","Innovation challenges","Enterprise development","Mentorship"]},
  {directorate:"Programmes",programme:"Mental Health Resilience",project:"Mental Health Resilience Project",activities:["Mental-health awareness","Psychosocial wellbeing education","Resilience building","Stress-management education","Peer support","Healthy-learning-environment activities","Referral/support linkages"]},
  {directorate:"Programmes",programme:"Suicide Prevention",project:"Suicide Prevention Project",activities:["Suicide-prevention awareness","Risk awareness","Prevention education","Peer support","Referral pathways","School/community awareness"]},
  {directorate:"Programmes",programme:"Keep Zambia Clean, Green and Healthy",project:"Keep Zambia Clean, Green and Healthy Project",activities:["Environmental awareness","Community clean-ups","Waste-management awareness","Tree planting","Environmental stewardship","Climate awareness","Community mobilisation","Sustainable-development education"]},
  {directorate:"Programmes",programme:"National Values and Principles Awareness",project:"National Values and Principles Awareness Project",activities:["National-values awareness","Responsible citizenship","Constitutional literacy","Ethical-leadership sessions","Student dialogues","Community dialogues","Public-awareness campaigns"]},
  {directorate:"Programmes",programme:"Voter Education",project:"Voter Education Project",activities:["Voter education","Civic education","Electoral awareness","Voter-registration awareness","Democratic-participation education","Community civic dialogues"]},
  {directorate:"Programmes",programme:"Health Promotion",project:"HP-P01 — Health Awareness & Education",projectCode:"HP-P01",activities:["HP-P01-A01 — Health education sessions","HP-P01-A02 — Disease prevention awareness","HP-P01-A03 — Health information campaigns","HP-P01-A04 — Community health talks","HP-P01-A05 — Health fairs","HP-P01-A06 — Peer health education"],activityAlignment:{"HP-P01-A01":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P01-A02":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P01-A03":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P01-A04":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3","SDG 10"]},"HP-P01-A05":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P01-A06":{"au":["Agenda 2063 Aspiration 1","Agenda 2063 Aspiration 6"],"sdgs":["SDG 3"]}}},
  {directorate:"Programmes",programme:"Health Promotion",project:"HP-P02 — Healthy Lifestyles & Wellness",projectCode:"HP-P02",activities:["HP-P02-A01 — Nutrition education","HP-P02-A02 — Healthy eating promotion","HP-P02-A03 — Physical activity and fitness","HP-P02-A04 — Healthy lifestyle campaigns","HP-P02-A05 — Wellness activities","HP-P02-A06 — Prevention of lifestyle-related diseases"],activityAlignment:{"HP-P02-A01":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 2","SDG 3"]},"HP-P02-A02":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 2","SDG 3"]},"HP-P02-A03":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P02-A04":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P02-A05":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P02-A06":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]}}},
  {directorate:"Programmes",programme:"Health Promotion",project:"HP-P03 — Adolescent & Youth Health",projectCode:"HP-P03",activities:["HP-P03-A01 — Adolescent health education","HP-P03-A02 — Sexual and reproductive health education","HP-P03-A03 — Menstrual health and hygiene","HP-P03-A04 — HIV/AIDS awareness and prevention","HP-P03-A05 — Youth-friendly health information"],activityAlignment:{"HP-P03-A01":{"au":["Agenda 2063 Aspiration 1","Agenda 2063 Aspiration 6"],"sdgs":["SDG 3"]},"HP-P03-A02":{"au":["Agenda 2063 Aspiration 1","Agenda 2063 Aspiration 6"],"sdgs":["SDG 3","SDG 5"]},"HP-P03-A03":{"au":["Agenda 2063 Aspiration 1","Agenda 2063 Aspiration 6"],"sdgs":["SDG 3","SDG 5","SDG 6"]},"HP-P03-A04":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P03-A05":{"au":["Agenda 2063 Aspiration 1","Agenda 2063 Aspiration 6"],"sdgs":["SDG 3","SDG 10"]}}},
  {directorate:"Programmes",programme:"Health Promotion",project:"HP-P04 — Mental Health & Psychosocial Wellbeing",projectCode:"HP-P04",activities:["HP-P04-A01 — Mental health awareness","HP-P04-A02 — Stress management education","HP-P04-A03 — Psychosocial wellbeing sessions","HP-P04-A04 — Resilience building","HP-P04-A05 — Peer support","HP-P04-A06 — Psychological first-aid awareness","HP-P04-A07 — Referral and support linkages"],activityAlignment:{"HP-P04-A01":{"au":["Agenda 2063 Aspiration 1","Agenda 2063 Aspiration 6"],"sdgs":["SDG 3"]},"HP-P04-A02":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P04-A03":{"au":["Agenda 2063 Aspiration 1","Agenda 2063 Aspiration 6"],"sdgs":["SDG 3"]},"HP-P04-A04":{"au":["Agenda 2063 Aspiration 1","Agenda 2063 Aspiration 6"],"sdgs":["SDG 3"]},"HP-P04-A05":{"au":["Agenda 2063 Aspiration 6"],"sdgs":["SDG 3","SDG 10"]},"HP-P04-A06":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P04-A07":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3","SDG 10"]}}},
  {directorate:"Programmes",programme:"Health Promotion",project:"HP-P05 — Substance Abuse Prevention",projectCode:"HP-P05",activities:["HP-P05-A01 — Alcohol and drug abuse awareness","HP-P05-A02 — Substance-use prevention education","HP-P05-A03 — Peer substance-abuse prevention","HP-P05-A04 — Substance-abuse awareness campaigns","HP-P05-A05 — Referral and support information"],activityAlignment:{"HP-P05-A01":{"au":["Agenda 2063 Aspiration 1","Agenda 2063 Aspiration 6"],"sdgs":["SDG 3"]},"HP-P05-A02":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P05-A03":{"au":["Agenda 2063 Aspiration 6"],"sdgs":["SDG 3","SDG 10"]},"HP-P05-A04":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P05-A05":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3","SDG 10"]}}},
  {directorate:"Programmes",programme:"Health Promotion",project:"HP-P06 — Community Health Outreach",projectCode:"HP-P06",activities:["HP-P06-A01 — Community health outreach","HP-P06-A02 — Health screening activities","HP-P06-A03 — Basic health checks","HP-P06-A04 — Health referral activities","HP-P06-A05 — Immunisation awareness","HP-P06-A06 — Blood donation awareness","HP-P06-A07 — Community health campaigns"],activityAlignment:{"HP-P06-A01":{"au":["Agenda 2063 Aspiration 1","Agenda 2063 Aspiration 6"],"sdgs":["SDG 3","SDG 10"]},"HP-P06-A02":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P06-A03":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P06-A04":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3","SDG 10"]},"HP-P06-A05":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P06-A06":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P06-A07":{"au":["Agenda 2063 Aspiration 1","Agenda 2063 Aspiration 6"],"sdgs":["SDG 3","SDG 10"]}}},
  {directorate:"Programmes",programme:"Health Promotion",project:"HP-P07 — Hygiene, Sanitation & Environmental Health",projectCode:"HP-P07",activities:["HP-P07-A01 — Personal hygiene education","HP-P07-A02 — Handwashing promotion","HP-P07-A03 — Sanitation awareness","HP-P07-A04 — Menstrual hygiene education","HP-P07-A05 — Waste-management and environmental-health awareness"],activityAlignment:{"HP-P07-A01":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P07-A02":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3","SDG 6"]},"HP-P07-A03":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3","SDG 6"]},"HP-P07-A04":{"au":["Agenda 2063 Aspiration 1","Agenda 2063 Aspiration 6"],"sdgs":["SDG 3","SDG 5","SDG 6"]},"HP-P07-A05":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3","SDG 6","SDG 12"]}}},
  {directorate:"Programmes",programme:"Health Promotion",project:"HP-P08 — First Aid & Health Safety",projectCode:"HP-P08",activities:["HP-P08-A01 — First-aid training","HP-P08-A02 — Basic health and safety training","HP-P08-A03 — Emergency preparedness","HP-P08-A04 — Injury-prevention awareness","HP-P08-A05 — Health and safety demonstrations"],activityAlignment:{"HP-P08-A01":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P08-A02":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P08-A03":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3","SDG 11"]},"HP-P08-A04":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]},"HP-P08-A05":{"au":["Agenda 2063 Aspiration 1"],"sdgs":["SDG 3"]}}},
  {directorate:"Policy, Advocacy & Research",programme:"Policy Research and Evidence",project:"Policy Research and Evidence Generation",activities:["Research studies","Surveys","Assessments","Data collection","Data analysis","Policy analysis","Evidence generation","Research dissemination"]},
  {directorate:"Policy, Advocacy & Research",programme:"Policy Research and Evidence",project:"Research Publications and Knowledge",activities:["Research reports","Policy briefs","Discussion papers","Technical papers","State of Students' reports","Research summaries","Knowledge products"]},
  {directorate:"Policy, Advocacy & Research",programme:"Advocacy and Policy Influence",project:"Evidence-Based Advocacy",activities:["Advocacy issue identification","Evidence development","Policy dialogues","Stakeholder consultations","Public awareness","Coalition building","Media engagement","Advocacy campaigns","Policy recommendations"]},
  {directorate:"Policy, Advocacy & Research",programme:"Advocacy and Policy Influence",project:"Policy and Legislative Engagement",activities:["Legislative monitoring","Policy monitoring","Analysis of proposed legislation","Policy positions","Technical submissions","Government engagement","Parliamentary engagement"]},
  {directorate:"Policy, Advocacy & Research",programme:"Policy Dialogue and Stakeholder Engagement",project:"Policy Dialogue Project",activities:["Policy roundtables","Stakeholder consultations","Public forums","Conferences","Workshops","Seminars","Expert dialogues"]},
  {directorate:"Policy, Advocacy & Research",programme:"Policy Dialogue and Stakeholder Engagement",project:"Student and Youth Policy Participation",activities:["Student consultations","Youth consultations","Youth policy forums","Student policy dialogues","Public-policy discussions","Youth participation platforms"]},
  {directorate:"Communications and Public Relations",programme:"Strategic Communications and Public Information",project:"VSI Public Information and Awareness",activities:["Public-awareness campaigns","Programme communication","Public information","Media engagement","Press releases","Public relations"]},
  {directorate:"Communications and Public Relations",programme:"Strategic Communications and Public Information",project:"Digital Communications and Media",activities:["Website content","Social media","Digital campaigns","Photography","Videography","Graphic design","Multimedia production","Digital audience engagement"]},
  {directorate:"Communications and Public Relations",programme:"Strategic Communications and Public Information",project:"Publications and Knowledge Dissemination",activities:["Newsletters","Annual reports","Programme publications","Research summaries","Success stories","Knowledge products","Public dissemination"]},
  {directorate:"Communications and Public Relations",programme:"Partnerships and Stakeholder Relations",project:"Strategic Partnerships Development",activities:["Partner identification","Stakeholder mapping","Partnership development","Institutional collaboration","MoUs/partnership arrangements","Partner engagement","Partnership reviews"]},
  {directorate:"Communications and Public Relations",programme:"Partnerships and Stakeholder Relations",project:"Stakeholder Engagement and Events",activities:["Stakeholder forums","Conferences","Workshops","Institutional meetings","Public events","Networking","Campaign events"]},
  {directorate:"Communications and Public Relations",programme:"Resource Mobilisation",project:"Fundraising and Resource Mobilisation",activities:["Funding-opportunity identification","Concept development","Proposal development","Fundraising campaigns","Donor engagement","Resource mobilisation"]},
  {directorate:"Communications and Public Relations",programme:"Resource Mobilisation",project:"Grants and Donor Relations",activities:["Grant-pipeline management","Grant applications","Grant negotiations","Donor stewardship","Grant reporting","Donor visibility"]}
];

export const DIRECTORATES=[
  "Programmes",
  "Policy, Advocacy & Research",
  "Communications and Public Relations",
  "Finance and Administration",
  "Monitoring, Evaluation, Accountability and Learning (MEAL)",
  "Directorate of Legal and Compliance"
];
export const PROGRAMMES=[...new Set([...PROGRAMME_REGISTER.map(x=>x.programme),"Other"] )];
export const PROJECTS=[...new Set([...PROGRAMME_REGISTER.map(x=>x.project),"Other"] )];
export const ACTIVITIES=[...new Set(PROGRAMME_REGISTER.flatMap(x=>x.activities))];
