export const PROGRAMME_REGISTER = [
  {directorate:"Programmes",programme:"Volunteer Management Project",project:"Volunteer Management Project",activities:["Volunteer recruitment","Volunteer induction","Volunteer training","Volunteer development","Volunteer deployment","Volunteer coordination","Volunteer recognition and retention"]},
  {directorate:"Programmes",programme:"Community Service and Volunteerism Project",project:"Community Service and Volunteerism Project",activities:["Community service","School/community outreach","On-campus training","Student volunteer activities","Community mobilisation","Community development activities","Social responsibility activities","Debate sessions"]},
  {directorate:"Programmes",programme:"Agriculture and Agro-processing Project",project:"Agriculture and Agro-processing Project",activities:["Agriculture skills training","Agro-processing training","Practical demonstrations","Entrepreneurship development","Value-chain development","Market linkage","Youth mentorship"]},
  {directorate:"Programmes",programme:"Technology and Innovation Entrepreneurship Project",project:"Technology and Innovation Entrepreneurship Project",activities:["Digital-skills training","Technology skills development","Innovation training","Entrepreneurship training","Innovation challenges","Enterprise development","Mentorship"]},
  {directorate:"Programmes",programme:"Mental Health Resilience Project",project:"Mental Health Resilience Project",activities:["Mental-health awareness","Psychosocial wellbeing education","Resilience building","Stress-management education","Peer support","Healthy-learning-environment activities","Referral/support linkages"]},
  {directorate:"Programmes",programme:"Suicide Prevention Project",project:"Suicide Prevention Project",activities:["Suicide-prevention awareness","Risk awareness","Prevention education","Peer support","Referral pathways","School/community awareness"]},
  {directorate:"Programmes",programme:"Keep Zambia Clean, Green and Healthy Project",project:"Keep Zambia Clean, Green and Healthy Project",activities:["Environmental awareness","Community clean-ups","Waste-management awareness","Tree planting","Environmental stewardship","Climate awareness","Community mobilisation","Sustainable-development education"]},
  {directorate:"Programmes",programme:"National Values and Principles Awareness",project:"National Values and Principles Awareness Project",activities:["National-values awareness","Responsible citizenship","Constitutional literacy","Ethical-leadership sessions","Student dialogues","Community dialogues","Public-awareness campaigns"]},
  {directorate:"Programmes",programme:"Voter Education",project:"Voter Education Project",activities:["Voter education","Civic education","Electoral awareness","Voter-registration awareness","Democratic-participation education","Community civic dialogues"]},
  {directorate:"Policy, Advocacy & Research",programme:"Policy Research and Evidence",project:"Policy Research and Evidence Generation",activities:["Research studies","Surveys","Assessments","Data collection","Data analysis","Policy analysis","Evidence generation","Research dissemination"]},
  {directorate:"Policy, Advocacy & Research",programme:"Policy Research and Evidence",project:"Research Publications and Knowledge",activities:["Research reports","Policy briefs","Discussion papers","Technical papers","State of Students' reports","Research summaries","Knowledge products"]},
  {directorate:"Policy, Advocacy & Research",programme:"Advocacy and Policy Influence",project:"Evidence-Based Advocacy",activities:["Advocacy issue identification","Evidence development","Policy dialogues","Stakeholder consultations","Public awareness","Coalition building","Media engagement","Advocacy campaigns","Policy recommendations"]},
  {directorate:"Policy, Advocacy & Research",programme:"Advocacy and Policy Influence",project:"Policy and Legislative Engagement",activities:["Legislative monitoring","Policy monitoring","Analysis of proposed legislation","Policy positions","Technical submissions","Government engagement","Parliamentary engagement"]},
  {directorate:"Policy, Advocacy & Research",programme:"Policy Dialogue and Stakeholder Engagement",project:"Policy Dialogue Project",activities:["Policy roundtables","Stakeholder consultations","Public forums","Conferences","Workshops","Seminars","Expert dialogues"]},
  {directorate:"Policy, Advocacy & Research",programme:"Policy Dialogue and Stakeholder Engagement",project:"Student and Youth Policy Participation",activities:["Student consultations","Youth consultations","Youth policy forums","Student policy dialogues","Public-policy discussions","Youth participation platforms"]},
  {directorate:"Communications and Public Relations",programme:"Strategic Communications and Public Information",project:"VSI Public Information and Awareness",activities:["Public-awareness campaigns","Programme communication","Public information","Media engagement","Press releases","Public relations"]},
  {directorate:"Communications and Public Relations",programme:"Strategic Communications and Public Information",project:"Digital Communications and Media",activities:["Website content","Social media","Digital campaigns","Photography","Videography","Graphic design","Multimedia production","Digital audience engagement"]},
  {directorate:"Communications and Public Relations",programme:"Strategic Communications and Public Information",project:"Publications and Knowledge Dissemination",activities:["Newsletters","Annual reports","Programme publications","Research summaries","Success stories","Knowledge products","Public dissemination"]},
  {directorate:"Communications and Public Relations",programme:"Partnerships and Stakeholder Relations",project:"Strategic Partnerships Development",activities:["Partner identification","Stakeholder mapping","Partnership development","Institutional collaboration","MoUs/partnership arrangements","Partner engagement","Partnership reviews"]},
  {directorate:"Communications and Public Relations",programme:"Partnerships and Stakeholder Relations",project:"Stakeholder Engagement and Events",activities:["Stakeholder forums","Conferences","Workshops","Institutional meetings","Public events","Networking","Campaign events"]},
  {directorate:"Communications and Public Relations",programme:"Resource Mobilisation",project:"Fundraising and Resource Mobilisation",activities:["Funding-opportunity identification","Concept development","Proposal development","Fundraising campaigns","Donor engagement","Resource mobilisation"]},
  {directorate:"Communications and Public Relations",programme:"Resource Mobilisation",project:"Grants and Donor Relations",activities:["Grant-pipeline management","Grant applications","Grant negotiations","Donor stewardship","Grant reporting","Donor visibility"]}
];

export const DIRECTORATES=[
  "Programmes",
  "Policy, Advocacy & Research",
  "Communications and Public Relations",
  "Finance and Administration",
  "Monitoring, Evaluation, Accountability and Learning (MEAL)",
  "Directorate of Legal and Compliance"
];
export const PROGRAMMES=[...new Set([...PROGRAMME_REGISTER.map(x=>x.programme),"Other"] )];
export const PROJECTS=[...new Set([...PROGRAMME_REGISTER.map(x=>x.project),"Other"] )];
export const ACTIVITIES=[...new Set(PROGRAMME_REGISTER.flatMap(x=>x.activities))];
