import { NextResponse } from "next/server";
import { pool } from "../../../../lib/db";
import { isAdminAuthenticated } from "../../../../lib/admin-auth";
const unauthorized=()=>NextResponse.json({error:"Admin authentication required."},{status:401});
async function ensureWebsiteBuilderTables(){
 await pool.query(`CREATE TABLE IF NOT EXISTS website_pages (id BIGSERIAL PRIMARY KEY,slug TEXT NOT NULL UNIQUE,title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published')),draft_content JSONB NOT NULL DEFAULT '[]'::jsonb,published_content JSONB NOT NULL DEFAULT '[]'::jsonb,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),published_at TIMESTAMPTZ)`);
 await pool.query(`CREATE TABLE IF NOT EXISTS website_page_versions (id BIGSERIAL PRIMARY KEY,page_id BIGINT NOT NULL REFERENCES website_pages(id) ON DELETE CASCADE,content JSONB NOT NULL,status TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
}
export async function GET(request){if(!isAdminAuthenticated(request))return unauthorized();try{await ensureWebsiteBuilderTables();const rows=(await pool.query("SELECT id,slug,title,status,draft_content,published_content,updated_at,published_at FROM website_pages ORDER BY id")).rows;return NextResponse.json({pages:rows});}catch(e){console.error(e);return NextResponse.json({error:"Unable to load website pages."},{status:500});}}
export async function POST(request){if(!isAdminAuthenticated(request))return unauthorized();try{await ensureWebsiteBuilderTables();const b=await request.json();const slug=String(b.slug||"").trim();const title=String(b.title||"").trim();if(!slug||!title)return NextResponse.json({error:"Page slug and title are required."},{status:400});const content=Array.isArray(b.content)?b.content:[];const r=await pool.query("INSERT INTO website_pages (slug,title,draft_content,status) VALUES ($1,$2,$3,'draft') ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title,draft_content=EXCLUDED.draft_content,updated_at=NOW() RETURNING *",[slug,title,JSON.stringify(content)]);await pool.query("INSERT INTO website_page_versions(page_id,content,status) VALUES($1,$2,'draft')",[r.rows[0].id,JSON.stringify(content)]);return NextResponse.json({page:r.rows[0]},{status:201});}catch(e){console.error(e);return NextResponse.json({error:"Unable to save page draft."},{status:500});}}
export async function PATCH(request){if(!isAdminAuthenticated(request))return unauthorized();try{await ensureWebsiteBuilderTables();const b=await request.json();const id=Number(b.id);if(!Number.isFinite(id))return NextResponse.json({error:"Invalid page."},{status:400});if(b.action==="publish"){const r=await pool.query("UPDATE website_pages SET published_content=draft_content,status='published',published_at=NOW(),updated_at=NOW() WHERE id=$1 RETURNING *",[id]);if(!r.rows[0])return NextResponse.json({error:"Page not found."},{status:404});await pool.query("INSERT INTO website_page_versions(page_id,content,status) VALUES($1,$2,'published')",[id,JSON.stringify(r.rows[0].published_content)]);return NextResponse.json({page:r.rows[0]});}return NextResponse.json({error:"Invalid action."},{status:400});}catch(e){console.error(e);return NextResponse.json({error:"Unable to publish page."},{status:500});}}