import {NextResponse} from "next/server";
import {ensureVolunteerTable,pool} from "../../../../lib/db";
import {isAdminAuthenticated} from "../../../../lib/admin-auth";

const unauthorized=()=>NextResponse.json({error:"Admin authentication required."},{status:401});
function hoursBetween(start,end){const [sh,sm]=String(start).split(":").map(Number),[eh,em]=String(end).split(":").map(Number);let mins=(eh*60+em)-(sh*60+sm);if(mins<0)mins+=1440;return Math.round((mins/60)*100)/100}
export async function GET(request){if(!isAdminAuthenticated(request))return unauthorized();try{await ensureVolunteerTable();const r=await pool.query(`SELECT a.*,v.full_name volunteer_name FROM volunteer_activity_register a JOIN volunteer_applications v ON v.id=a.volunteer_id ORDER BY a.activity_date DESC,a.start_time DESC`);return NextResponse.json({activities:r.rows});}catch(e){console.error(e);return NextResponse.json({error:"Unable to load activity register."},{status:500})}}
export async function POST(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();if(!b.volunteer_id||!b.activity_date||!b.activity_name||!b.start_time||!b.end_time)return NextResponse.json({error:"Volunteer, date, activity, start time and end time are required."},{status:400});const hours=hoursBetween(b.start_time,b.end_time);if(hours<=0)return NextResponse.json({error:"Activity duration must be greater than zero."},{status:400});await ensureVolunteerTable();const r=await pool.query(`INSERT INTO volunteer_activity_register (volunteer_id,activity_date,activity_name,project,location,start_time,end_time,hours,description,supervisor_name,verified) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[b.volunteer_id,b.activity_date,b.activity_name,b.project||null,b.location||null,b.start_time,b.end_time,hours,b.description||null,b.supervisor_name||null,!!b.verified]);return NextResponse.json({ok:true,activity:r.rows[0]},{status:201});}catch(e){console.error(e);return NextResponse.json({error:"Unable to record activity."},{status:500})}}
export async function DELETE(request){if(!isAdminAuthenticated(request))return unauthorized();try{const b=await request.json();if(!b.id)return NextResponse.json({error:"Activity ID is required."},{status:400});await ensureVolunteerTable();const r=await pool.query("DELETE FROM volunteer_activity_register WHERE id=$1 RETURNING id",[b.id]);if(!r.rowCount)return NextResponse.json({error:"Activity not found."},{status:404});return NextResponse.json({ok:true,id:r.rows[0].id});}catch(e){console.error(e);return NextResponse.json({error:"Unable to delete activity."},{status:500})}}
