import "../../elearning.css";
import { SiteHeader, SiteFooter } from "../../components/SiteChrome";

export const metadata = {
  title: "Generosity, Volunteerism and Community Service | VSI E-Learning",
  description: "Teaching notes on generosity, volunteerism, active citizenship and community service for secondary school students.",
  alternates: { canonical: "/elearning/community-service" },
};

const communityAssets = [["Young people", "Provide labour, ideas and energy."], ["Teachers", "Provide guidance and learning support."], ["Traditional leaders", "Mobilise and encourage the community."], ["Local council", "Provide technical support and local coordination."], ["Churches and mosques", "Mobilise volunteers and community support."], ["Businesses", "Provide materials, services or sponsorship."], ["Health workers", "Provide health information and technical advice."], ["Schools", "Provide meeting spaces and organised groups."], ["Community groups", "Organise local activities and participation."]];
const actionSteps = [["01", "Meet with local leaders and stakeholders", "Build agreement and local ownership before starting."], ["02", "Identify the people and places most affected", "Focus effort where the need is greatest."], ["03", "Mobilise volunteers", "Invite students and community members to participate."], ["04", "Carry out the agreed activity", "Put the plan into practical action."], ["05", "Communicate the message", "Explain the purpose of the activity and encourage positive behaviour."], ["06", "Encourage continued participation", "Support behaviour change beyond the first activity."], ["07", "Follow up", "Check progress and improve the approach over time."]];
const projectSteps = [["01", "Identify the problem", "The school has poor care of a shared public facility."], ["02", "Identify people affected", "Students, teachers, workers and visitors."], ["03", "Identify available resources", "Students, teachers, school facilities, local skills and community members."], ["04", "Develop the solution", "Organise a simple service activity and awareness campaign with those who use the facility."], ["05", "Assign responsibilities", "Team leader, mobilisation officer, communications officer, materials coordinator and monitoring officer."], ["06", "Measure success", "Look for better care of the facility, stronger participation and continued responsible use."]];
const successIndicators = ["The identified problem is reduced.", "More people take responsibility for the shared resource.", "More young people participate in the activity.", "The improvement is maintained after the first activity."];
const activeCitizenTraits = [["01", "Care", "Pay attention to what happens in your school and community."], ["02", "Respect", "Treat other people with dignity, fairness and consideration."], ["03", "Responsibility", "Follow rules and laws and protect public property."], ["04", "Participation", "Take part in community activities and opportunities to help."], ["05", "Voice", "Speak up about problems in a respectful and constructive way."], ["06", "Collaboration", "Work with others to find practical solutions."]];
const communityChallenges = ["Littering", "Poor sanitation", "Bullying", "Environmental destruction", "Lack of reading materials", "Unsafe public spaces", "Poor care of public facilities", "Lack of support for vulnerable people"];
const takeaways = ["Generosity means giving and helping others.", "Volunteerism is freely giving your time, skills or effort.", "Community service helps address local problems.", "Active citizens take responsibility for their communities.", "Communities have local resources and skills that can be used to solve problems.", "Young people can lead and participate in community development.", "Partnerships make community action more effective.", "Good community service starts by understanding a problem, planning carefully, acting with others and checking what changed."];

export default function CommunityServicePage() {
  return (
    <main>
      <SiteHeader />
      <section className="lesson-hero"><div className="section-shell"><a className="lesson-back" href="/elearning">← Back to E-Learning</a><p className="kicker light">MODULE 02 · VSI E-LEARNING</p><h1>Generosity, Volunteerism <em>and Community Service.</em></h1><p className="lesson-subtitle">Teaching Notes for Secondary School Students</p><div className="lesson-meta"><span><strong>2 Hours</strong> Duration</span><span><strong>SDG 11 &amp; 17</strong> Sustainable Communities &amp; Partnerships</span><span><strong>AU Goal 18</strong> Engaged and empowered youth and children</span></div></div></section>
      <article className="lesson-content section-shell">
        <section className="lesson-section"><p className="kicker">01 · FOUNDATIONS</p><h2>Understanding Generosity, Volunteerism <em>and Community Service.</em></h2><div className="lesson-card-list"><div className="lesson-row-card"><span className="module-label">GENEROSITY</span><h3>Giving without expecting something in return.</h3><p>Generosity means being willing to give, share or help others without expecting something in return. It is not only about money. We can give our time, skills, knowledge, food or clothing, ideas, encouragement and support to people in need.</p><div className="lesson-note"><strong>Example</strong><p>A student who shares learning materials with a classmate who cannot afford them is showing generosity.</p></div></div><div className="lesson-row-card"><span className="module-label">VOLUNTEERISM</span><h3>Freely offering time, skills or effort.</h3><p>Volunteerism means freely offering your time, skills or effort to help other people or improve your community. A volunteer does not necessarily expect payment.</p><div className="bullet-grid compact"><p>Helping elderly people with household tasks.</p><p>Supporting a school club.</p><p>Helping younger pupils with reading or mathematics.</p><p>Assisting at a community information activity.</p><p>Sharing useful skills with others.</p><p>Helping organise a youth activity.</p></div></div><div className="lesson-row-card"><span className="module-label">COMMUNITY SERVICE</span><h3>Turning concern into practical local action.</h3><p>Community service is work done by individuals or groups to improve the lives of people in their community. It can involve identifying a problem and working together to find a practical solution.</p><div className="lesson-note"><strong>Example</strong><p>Young people notice that a shared community facility is not being well cared for. They work with the people who use it to agree on a simple improvement plan and share responsibilities.</p></div></div></div></section>

        <section className="lesson-section active-citizenship-section">
          <div className="active-citizenship-header"><div><p className="kicker">02 · ACTIVE CITIZENSHIP</p><h2>Be an <em>Active Citizen.</em></h2><p className="active-citizen-lead">An active citizen takes responsibility for helping make their school and community a better place.</p></div><div className="active-citizen-badge" aria-hidden="true"><span>02</span><small>ACTIVE<br />CITIZENSHIP</small></div></div>
          <div className="active-citizen-grid">{activeCitizenTraits.map(([number, title, text]) => <article className="active-citizen-card" key={number}><span className="active-citizen-number">{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div>
          <div className="active-citizen-principle"><div className="principle-mark">!</div><div><span className="module-label">REMEMBER</span><h3>Young people are part of the solution.</h3><p>Being an active citizen is not about waiting for someone else to solve every problem. Young people can contribute ideas, effort and leadership to positive change.</p></div></div>
          <div className="active-citizen-discussion"><div className="discussion-intro"><span className="module-label">DISCUSSION ACTIVITY</span><h3>What problems can young people help solve?</h3><p>Invite learners to identify problems in their school or community and discuss where young people can make a practical contribution.</p></div><div className="challenge-grid">{communityChallenges.map((item, index) => <div className="challenge-card" key={item}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></div>)}</div></div>
        </section>

        <section className="lesson-section"><p className="kicker">03 · FROM IDEA TO ACTION</p><h2>Understand the Problem <em>Before Acting.</em></h2><p>Good community service starts with understanding the problem. Before choosing an activity, ask four simple questions.</p><div className="case-grid four-up"><div><span>01</span><h3>What is the problem?</h3><p>Describe the issue clearly and specifically.</p></div><div><span>02</span><h3>Who is affected?</h3><p>Identify the people, places or groups experiencing the problem.</p></div><div><span>03</span><h3>Why does it exist?</h3><p>Look at possible causes rather than only the visible symptoms.</p></div><div><span>04</span><h3>What can we do?</h3><p>Choose an action that is realistic with the resources available.</p></div></div><div className="lesson-card-list single-card"><div className="lesson-row-card"><span className="module-label">WORKED EXAMPLE · SHARED COMMUNITY FACILITY</span><h3>A shared facility is not being well cared for.</h3><p><strong>People affected:</strong> Young people, families, workers and other users.</p><p><strong>Possible causes:</strong> Unclear responsibilities, limited information, weak follow-up and poor coordination.</p><p><strong>Possible action:</strong> Bring users together, agree on responsibilities, organise a service activity and check whether the improvement lasts.</p></div></div></section>
        <section className="lesson-section"><p className="kicker">04 · ASSET MAPPING</p><h2>Use What the Community <em>Already Has.</em></h2><p>Asset mapping means identifying the people, organisations, skills, facilities and resources available in a community. A community may already have many resources that can help solve a problem.</p><div className="lesson-table-wrap"><table className="lesson-table"><thead><tr><th>Community asset</th><th>How it can help</th></tr></thead><tbody>{communityAssets.map(([asset, help]) => <tr key={asset}><td>{asset}</td><td>{help}</td></tr>)}</tbody></table></div><div className="lesson-note emphasis"><strong>Important lesson</strong><p>A community does not have to wait for outside organisations before taking action. Local people often have knowledge, skills and resources that can be used to address local problems.</p></div></section>
        <section className="lesson-section"><p className="kicker">05 · ACTION PLANNING</p><h2>Turn a Community Problem into an <em>Action Plan.</em></h2><div className="lesson-row-card action-plan-card"><span className="module-label">PROBLEM</span><h3>Poor care of a shared community facility.</h3><p><strong>Goal:</strong> Improve care, use and shared responsibility for the facility.</p><div className="action-plan-list">{actionSteps.map(([number, title, text]) => <div key={number}><span>{number}</span><div><strong>{title}</strong><p>{text}</p></div></div>)}</div></div><div className="lesson-card-list two-column"><div className="lesson-row-card"><span className="module-label">RESOURCES NEEDED</span><p>People · Information · Basic materials · Transport where necessary · Communication materials · Volunteers</p></div><div className="lesson-row-card"><span className="module-label">PEOPLE TO INVOLVE</span><p>Students · Teachers · Local leaders · Council representatives · Community members · Relevant organisations</p></div></div></section>
        <section className="lesson-section"><p className="kicker">06 · WORKING TOGETHER</p><h2>Experience, Plan, <em>Participate.</em></h2><div className="lesson-activity"><span className="module-label">EXPERIENCE SHARING</span><h3>Share what you have learned through helping others.</h3><div className="bullet-grid compact"><p>Have you ever volunteered to help someone?</p><p>What did you do?</p><p>Why did you decide to help?</p><p>What did you learn?</p><p>How did the person or community benefit?</p><p>What would you do differently next time?</p></div></div><div className="lesson-card-list single-card"><div className="lesson-row-card"><span className="module-label">GROUP ACTIVITY · DESIGN A COMMUNITY SERVICE PROJECT</span><h3>My Community, Our Action</h3><p>Divide students into small groups. Each group should identify one problem in their school or community and develop a simple community service project.</p><div className="action-plan-list project-steps">{projectSteps.map(([number, title, text]) => <div key={number}><span>{number}</span><div><strong>{title}</strong><p>{text}</p></div></div>)}</div></div></div></section>
        <section className="lesson-section"><p className="kicker">07 · MEASURING CHANGE</p><h2>How Will We Know the Project <em>Worked?</em></h2><p>Community action becomes stronger when groups decide in advance what success should look like.</p><div className="bullet-grid">{successIndicators.map((item) => <p key={item}>{item}</p>)}</div><div className="lesson-note emphasis"><strong>Key lesson</strong><p>Small actions can create meaningful change. A young person does not need to have a lot of money to serve their community.</p><p><strong>TIME + SKILLS + IDEAS + TEAMWORK = COMMUNITY ACTION</strong></p><p>When young people work together, they can help create cleaner, safer and stronger communities.</p></div></section>
        <section className="lesson-section"><p className="kicker">08 · DEVELOPMENT ALIGNMENT</p><h2>Community Service Supports <em>Development Goals.</em></h2><div className="lesson-card-list two-column"><div className="lesson-row-card"><span className="module-label">SDG 11</span><h3>Sustainable Cities and Communities</h3><p>Volunteerism and community service can help create communities that are safer, more inclusive, better organised and responsive to local needs.</p><div className="lesson-note"><strong>Example</strong><p>Young people can contribute to community activities that improve shared spaces, access to learning and local participation.</p></div></div><div className="lesson-row-card"><span className="module-label">SDG 17</span><h3>Partnerships for the Goals</h3><p>Community problems are easier to solve when people work together. Young people can partner with schools, local councils, community organisations, businesses, civil society organisations and traditional or community leaders.</p><div className="lesson-note"><strong>Key message</strong><p>Partnership makes community action stronger.</p></div></div></div></section>
        <section className="lesson-closing"><p className="kicker">09 · FINAL CLASS ACTIVITY</p><h2>My Community, <em>My Responsibility.</em></h2><div className="reflection-grid"><div><span>01</span><strong>One problem I see in my community</strong><p>________________________________</p></div><div><span>02</span><strong>One thing young people can do about it</strong><p>________________________________</p></div><div><span>03</span><strong>One person or organisation we can work with</strong><p>________________________________</p></div><div><span>04</span><strong>One action I am willing to take</strong><p>________________________________</p></div></div><div className="closing-message"><strong>Closing message</strong><p>You do not have to wait until you are older to make a difference. Start where you are, use what you have, work with others, and serve your community.</p></div><div className="lesson-note emphasis"><strong>Next: From service to environmental action</strong><p>Module 03 takes one area of community action deeper: keeping Zambia clean, green and healthy.</p></div></section>
        <section className="lesson-section lesson-takeaways"><p className="kicker">10 · KEY TAKEAWAYS</p><h2>Remember the <em>essentials.</em></h2><div className="focus-list mini-focus">{takeaways.map((item, index) => <div key={item}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></div>)}</div></section>
      </article>
      <SiteFooter />
    </main>
  );
}
