"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import styles from "./chrome-manager.module.css";

const base={header:{links:[["Discover VSI","/discover"],["Our work","/#work"],["Our story","/story"],["Community","/community"],["VSI News","/news"],["Events","/events"],["Volunteer","/volunteer"],["Contact","/#contact"]],ctaLabel:"Volunteer",ctaHref:"/volunteer"},footer:{brandText:"Promoting policies and initiatives that place students at the centre of national development.",explore:[["Home","/"],["Discover VSI","/discover"],["Our work","/#work"],["Our story","/story"],["VSI in the Community","/community"],["VSI News","/news"],["Events","/events"],["Volunteer","/volunteer"]],email:"vsizambia@gmail.com",phone:"+260 968 623 786",address:"Plot No. 9173, Ben Bella Road\nPeace Embassy Building, 1st Floor\nLusaka, Zambia"}};

export default function ChromeManager(){
 const [tab,setTab]=useState("header");
 const [data,setData]=useState(base);
 const [notice,setNotice]=useState("");
 const [busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/admin/website-chrome",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>{if(!d)return;const next={...base};(d.chrome||[]).forEach(x=>{next[x.chrome_key]=x.draft_content||base[x.chrome_key]});setData(next)}).catch(()=>{})},[]);
 const cfg=data[tab];const key=tab==="header"?"links":"explore";const links=cfg[key];
 function setLink(i,p){setData(d=>({...d,[tab]:{...d[tab],[key]:d[tab][key].map((x,j)=>j===i?[p.label??x[0],p.href??x[1]]:x)}}))}
 function add(){setData(d=>({...d,[tab]:{...d[tab],[key]:[...d[tab][key],["New link","/"]]}}))}
 function remove(i){setData(d=>({...d,[tab]:{...d[tab],[key]:d[tab][key].filter((_,j)=>j!==i)}}))}
 function move(i,dir){setData(d=>{const a=[...d[tab][key]],j=i+dir;if(j<0||j>=a.length)return d;[a[i],a[j]]=[a[j],a[i]];return {...d,[tab]:{...d[tab],[key]:a}}})}
 async function save(){setBusy(true);setNotice("");try{const r=await fetch("/api/admin/website-chrome",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:tab,content:cfg})});const x=await r.json();if(!r.ok)throw Error(x.error);setNotice("Draft saved.")}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 async function publish(){await save();setBusy(true);try{const r=await fetch("/api/admin/website-chrome",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:tab})});const x=await r.json();if(!r.ok)throw Error(x.error);setNotice("Published.")}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 return <main className={styles.page}><div className={styles.shell}><div className={styles.top}><Link href="/admin/website-manager">← Visual Page Builder</Link><span>WEBSITE CHROME</span></div><section className={styles.hero}><div><p>VSI WEBSITE MANAGEMENT</p><h1>Menu & Footer Builder</h1><span>Manage the navigation and footer structure from one place.</span></div><div><button onClick={save} disabled={busy}>Save draft</button><button className={styles.publish} onClick={publish} disabled={busy}>Publish</button></div></section>{notice&&<p className={styles.notice}>{notice}</p>}<div className={styles.tabs}><button className={tab==="header"?styles.active:""} onClick={()=>setTab("header")}>Navigation menu</button><button className={tab==="footer"?styles.active:""} onClick={()=>setTab("footer")}>Footer</button></div><div className={styles.grid}><section className={styles.panel}><h2>{tab==="header"?"Navigation links":"Explore links"}</h2><p>Reorder, rename or add links. Save as a draft before publishing.</p>{links.map((x,i)=><div className={styles.linkRow} key={i}><span>{i+1}</span><input value={x[0]} onChange={e=>setLink(i,{label:e.target.value})}/><input value={x[1]} onChange={e=>setLink(i,{href:e.target.value})}/><button onClick={()=>move(i,-1)}>↑</button><button onClick={()=>move(i,1)}>↓</button><button className={styles.remove} onClick={()=>remove(i)}>×</button></div>)}<button className={styles.add} onClick={add}>＋ Add link</button></section><aside className={styles.panel}><h2>{tab==="header"?"Header call-to-action":"Footer contact"}</h2>{tab==="header"?<><label>Button label<input value={cfg.ctaLabel} onChange={e=>setData(d=>({...d,header:{...d.header,ctaLabel:e.target.value}}))}/></label><label>Button link<input value={cfg.ctaHref} onChange={e=>setData(d=>({...d,header:{...d.header,ctaHref:e.target.value}}))}/></label></>:<><label>Organisation description<textarea value={cfg.brandText} onChange={e=>setData(d=>({...d,footer:{...d.footer,brandText:e.target.value}}))}/></label><label>Email<input value={cfg.email} onChange={e=>setData(d=>({...d,footer:{...d.footer,email:e.target.value}}))}/></label><label>Phone<input value={cfg.phone} onChange={e=>setData(d=>({...d,footer:{...d.footer,phone:e.target.value}}))}/></label><label>Address<textarea value={cfg.address} onChange={e=>setData(d=>({...d,footer:{...d.footer,address:e.target.value}}))}/></label></>}</aside></div><section className={styles.note}><strong>Safe rollout:</strong> this builder stores and publishes chrome configuration separately. The existing live header/footer stays untouched until the public SiteChrome component is switched to read the published configuration.</section></div></main>;
}
