import {NextResponse} from "next/server";
import {pool,ensureVolunteerTable,ensureNewsTable,ensureEventsTable,ensureDataProtectionTables,ensureVolunteerFinanceTables} from "../../../../lib/db";
import {isAdminAuthenticated} from "../../../../lib/admin-auth";
const unauthorized=()=>NextResponse.json({error:"Admin authentication required."},{status:401});
export async function GET(request){
 if(!isAdminAuthenticated(request))return unauthorized();
 try{
  await Promise.all([ensureVolunteerTable(),ensureNewsTable(),ensureEventsTable(),ensureDataProtectionTables(),ensureVolunteerFinanceTables()]);
  const [volunteers,volunteerHours,professionalDevelopmentHours,news,events,registrations,catalogue,complianceRequests,complianceIncidents,retentionDue,finance]=await Promise.all([
   pool.query("SELECT COUNT(*) FILTER (WHERE status='approved')::int approved,COUNT(*) FILTER (WHERE status='pending')::int pending FROM volunteer_applications"),
   pool.query("SELECT COALESCE(SUM(a.hours),0) total_hours FROM volunteer_activity_register a JOIN volunteer_applications v ON v.id=a.volunteer_id WHERE v.status='approved' AND a.verified=true AND UPPER(TRIM(COALESCE(a.activity_code,''))) NOT LIKE 'FAHR%'"),
   pool.query("SELECT COALESCE(SUM(hours),0) total_hours FROM (SELECT a.hours FROM volunteer_activity_register a JOIN volunteer_applications v ON v.id=a.volunteer_id WHERE v.status='approved' AND a.verified=true AND UPPER(TRIM(COALESCE(a.activity_code,''))) LIKE 'FAHR%' UNION ALL SELECT pd.hours FROM volunteer_professional_development pd JOIN volunteer_applications v ON v.id=pd.volunteer_id WHERE v.status='approved' AND pd.status='COMPLETED') development_sources"),
   pool.query("SELECT COUNT(*) FILTER (WHERE status='published')::int published,COUNT(*) FILTER (WHERE status='draft')::int drafts,COUNT(*)::int total FROM news_articles"),
   pool.query("SELECT COUNT(*) FILTER (WHERE event_date>=CURRENT_DATE AND status='published')::int upcoming,COUNT(*) FILTER (WHERE event_date<CURRENT_DATE)::int completed FROM vsi_events"),
   pool.query("SELECT COUNT(*)::int total FROM vsi_event_registrations"),
   pool.query("SELECT COUNT(*) FILTER (WHERE active=true)::int activities,COUNT(DISTINCT project) FILTER (WHERE active=true AND NULLIF(TRIM(project),'') IS NOT NULL)::int projects,COUNT(DISTINCT directorate) FILTER (WHERE active=true)::int directorates FROM vsi_master_activity_catalogue"),
   pool.query("SELECT COUNT(*) FILTER (WHERE status IN ('received','in_progress'))::int requests FROM data_protection_requests"),
   pool.query("SELECT COUNT(*) FILTER (WHERE status IN ('open','contained','investigating'))::int incidents FROM data_protection_incidents"),
   pool.query("SELECT (SELECT COUNT(*) FROM volunteer_applications WHERE created_at + INTERVAL '60 months' <= NOW()) + (SELECT COUNT(*) FROM volunteer_activity_register WHERE created_at + INTERVAL '84 months' <= NOW()) + (SELECT COUNT(*) FROM data_protection_requests WHERE received_at + INTERVAL '36 months' <= NOW()) + (SELECT COUNT(*) FROM data_protection_incidents WHERE reported_at + INTERVAL '84 months' <= NOW()) AS due"),
   pool.query("SELECT COALESCE(SUM(amount_paid),0) membership_paid,COALESCE(SUM(CASE WHEN status IN ('unpaid','partial') THEN GREATEST(amount_due-amount_paid,0) ELSE 0 END),0) outstanding,(SELECT COALESCE(SUM(amount),0) FROM volunteer_donations) donations,(SELECT COALESCE(SUM(amount),0) FROM volunteer_finance_spending) total_spent FROM volunteer_membership_payments"),
  ]);
  return NextResponse.json({volunteers:{approved:volunteers.rows[0]?.approved||0,pending:volunteers.rows[0]?.pending||0,verifiedHours:Number(volunteerHours.rows[0]?.total_hours||0),professionalDevelopmentHours:Number(professionalDevelopmentHours.rows[0]?.total_hours||0)},news:{published:news.rows[0]?.published||0,drafts:news.rows[0]?.drafts||0,total:news.rows[0]?.total||0},events:{upcoming:events.rows[0]?.upcoming||0,registrations:registrations.rows[0]?.total||0,completed:events.rows[0]?.completed||0},catalogue:{activities:catalogue.rows[0]?.activities||0,projects:catalogue.rows[0]?.projects||0,directorates:catalogue.rows[0]?.directorates||0},compliance:{requests:complianceRequests.rows[0]?.requests||0,incidents:complianceIncidents.rows[0]?.incidents||0,retentionDue:retentionDue.rows[0]?.due||0,retentionOverdue:retentionDue.rows[0]?.due||0},finance:{membershipPaid:Number(finance.rows[0]?.membership_paid||0),outstanding:Number(finance.rows[0]?.outstanding||0),donations:Number(finance.rows[0]?.donations||0),totalSpent:Number(finance.rows[0]?.total_spent||0)}});
 }catch(e){console.error("Admin dashboard summary failed:",e);return NextResponse.json({error:"Unable to load dashboard summaries."},{status:500});}
}