"use client";
import {useEffect,useState} from "react";
import {SiteFooter,SiteHeader} from "../../../components/SiteChrome";

export default function AdminAuthenticatorSetup(){
  const [data,setData]=useState(null),[error,setError]=useState(""),[copied,setCopied]=useState(false);
  useEffect(()=>{fetch("/api/admin/authenticator",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load authenticator setup.");setData(d)}).catch(e=>setError(e.message))},[]);
  async function copy(){if(!data)return;await navigator.clipboard.writeText(data.secret);setCopied(true);setTimeout(()=>setCopied(false),1800)}
  return <><SiteHeader ctaLabel="Admin" ctaHref="/admin/volunteers"/><main style={{minHeight:"70vh",padding:"80px 20px",background:"#f6f9fc"}}><div style={{maxWidth:680,margin:"0 auto",background:"#fff",borderRadius:20,padding:32,boxShadow:"0 16px 45px rgba(11,48,82,.10)"}}><p className="kicker">ADMIN SECURITY</p><h1 style={{marginBottom:10}}>Authenticator setup</h1><p style={{color:"#52606d",lineHeight:1.6}}>Add the VSI Admin account to Google Authenticator, Microsoft Authenticator or Authy. This page is only available while you are already signed in as an administrator.</p>{error&&<div style={{marginTop:20,padding:14,borderRadius:10,background:"#fff0f0",color:"#a12b2b"}}>{error}</div>}{data&&<><div style={{marginTop:24,padding:20,borderRadius:14,background:"#f4f8fc",border:"1px solid #dce7f1"}}><b>Account</b><div style={{marginTop:5}}>{data.account}</div><b style={{display:"block",marginTop:16}}>Issuer</b><div style={{marginTop:5}}>{data.issuer}</div><b style={{display:"block",marginTop:16}}>Manual setup key</b><div style={{marginTop:8,fontFamily:"monospace",fontSize:18,letterSpacing:1.5,wordBreak:"break-all"}}>{data.secret}</div><button type="button" onClick={copy} style={{marginTop:12,border:0,borderRadius:10,padding:"10px 14px",fontWeight:800,cursor:"pointer"}}>{copied?"Copied ✓":"Copy setup key"}</button></div><div style={{marginTop:22,lineHeight:1.7,color:"#52606d"}}><b>In your Authenticator app:</b><ol><li>Choose <b>Add account</b> or <b>+</b>.</li><li>Choose <b>Enter setup key manually</b>.</li><li>Account name: <b>VSI Admin</b>.</li><li>Paste the setup key above.</li><li>Use <b>Time-based (TOTP)</b> and save.</li></ol><p>After this, the VSI Admin login will require the 6-digit code from the app after the password is accepted.</p></div></>}</div></main><SiteFooter/></>;
}
